ecadlabs/taquito

example/contract-origination.ts, integration-tests/contract-api-scenario.spec.ts, packages/taquito-rpc/src/taquito-rpc.ts, packages/taquito-rpc/test/taquito-rpc.spec.ts, packages/taquito/src/contract/estimate.ts, packages/taquito/src/contract/interface.ts, packages/taquito/src/contract/naive-estimate-provider.ts, packages/taquito/src/contract/prepare.ts, packages/taquito/src/contract/rpc-contract-provider.ts, packages/taquito/src/contract/rpc-estimate-provider.ts, packages/taquito/src/operations/operation-emitter.ts, packages/taquito/src/operations/origination-operation.ts, packages/taquito/src/taquito.ts, packages/taquito/src/tz/rpc-tz-provider.ts, packages/taquito/test/contract/estimate.spec.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts, packages/taquito/test/contract/rpc-estimate-provider.spec.ts, packages/taquito/test/operations/origination-operation.spec.ts
Now expose an estimation api to estimate origination and transfer. 
The same api is used internally
to infer default gas, storage and fee parameter when sending transaction or originating contract
re #88, #121
=> feat(taquito): Add fees estimation feature

packages/taquito/patch.js
What worries me is that Angular Truffle Box, Ethereum Web3.js, and now Taquito all have different path for angular web pack config.
[Ethereum Web3.js patch](https://github.com/ethereum/web3.js/blob/2.x/packages/web3/angular-patch.js) points to `'../../node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js'`
[Angular Truffle Box patch](https://github.com/Quintor/angular-truffle-box/blob/master/patch.js) points to `'node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js'`
Taquito patch points to `'../../@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js'`
This makes me believe that either my local test didn't do what `npm install` does or NPM has changed the CWD of post …
=> Fixed angular webpack config path in postinstall patch script

packages/taquito/src/context.ts, packages/taquito/src/forger/interface.ts, packages/taquito/src/forger/rpc-forger.ts, packages/taquito/src/operations/operation-emitter.ts, packages/taquito/src/taquito.ts
Abstract operation forging with a forger interface and move the actual implementation to an RPC provider as the default
This change will be useful to allow swapping operation forging implementation when we implement #108
=> Extract forger provider into it's own provider

packages/taquito/src/contract/errors.ts, packages/taquito/src/contract/rpc-contract-provider.ts, packages/taquito/src/operations/operation-emitter.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts
Throw an explicit error for invalid delegation source in Babylon
- Add an error for invalid delegation source
- Make sure that source of reveal operation is the implicit account sending the operation.
=> fix(taquito) Throw an explicit error for invalid delegation source

integration-tests/contract-api-scenario.spec.ts, packages/taquito/src/context.ts, packages/taquito/src/operations/operations.ts, packages/taquito/test/operations/origination-operation.spec.ts
BREAKING CHANGE: Default confirmation counter is now 1 and it must be greater than 1 if specified
fix #202
=> fix(taquito): Fix wrong confirmation count for operation.confirmation

integration-tests/config.ts, integration-tests/contract-api-scenario.spec.ts, integration-tests/data/badCode.ts, integration-tests/data/failwith.ts, integration-tests/manager-contract-scenario.spec.ts, packages/taquito-rpc/src/types.ts, packages/taquito/src/contract/rpc-estimate-provider.ts, packages/taquito/src/operations/operation-emitter.ts, packages/taquito/src/operations/operation-errors.ts, packages/taquito/src/taquito.ts, packages/taquito/test/contract/helper.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts, packages/taquito/test/contract/rpc-estimate-provider.spec.ts
Failed operation will now throw compliant JS error with more information attached to it
BREAKING CHANGE: 
- Operation failed error API changed to be compliant with standard JS error
- RPC estimator can now throw operation failed error
fix #223
Misc:
- Add configuration for known baker and contract in integration test
- Add integration test with a contract that use the FAILWITH operation
=> Sensible error for failed operation

integration-tests/config.ts, packages/taquito/src/context.ts, packages/taquito/src/forger/composite-forger.ts, packages/taquito/src/taquito.ts, packages/taquito/test/forger/composite-forger.spec.ts
Composite forger allow to use multiple forger implementation in parallel and assert they all return
the same result
re #108
=> feat(taquito): Add the composite forger

.gitignore, packages/taquito/README.md, packages/taquito/package-lock.json, packages/taquito/package.json, packages/taquito/update-readme.js, packages/taquito/webpack.config.js
Add the following step to the cdn bundle build task:
- Compute integrity checksum from minified cdn bundle
- Update the script example in the readme using the new integrity checksum and version of the package
=> build(taquito): Compute checksum and update cdn script example on build

integration-tests/batch-api.spec.ts, integration-tests/package.json, packages/taquito-rpc/src/opkind.ts, packages/taquito-rpc/src/taquito-rpc.ts, packages/taquito-rpc/src/types.ts, packages/taquito/src/batch/rpc-batch-provider.ts, packages/taquito/src/contract/prepare.ts, packages/taquito/src/contract/rpc-estimate-provider.ts, packages/taquito/src/forger/interface.ts, packages/taquito/src/operations/operation-emitter.ts, packages/taquito/src/operations/origination-operation.ts, packages/taquito/src/operations/types.ts, packages/taquito/src/taquito.ts, packages/taquito/src/tz/rpc-tz-provider.ts
Removed constructed operation type and leverage type inference when mapping operation from user
parameter to RPC compliant object
=> refactor(taquito): Refactor operation content types to use enum

README.md
It might be useful for developers to grok the latest version of Taquito quickly from the README. I'm not sure however if the badge is always accurate (if a "pre-release" version is published with the `latest` dist-tag for example), so if not feel free to close this!
=> docs(readme): Add npm version badge

docs/making_transfers.md, docs/quick_start.md, docs/set_delegate.md, docs/smartcontracts.md, packages/taquito/README.md
This updates all docs examples to use Carthagenet and renders the injection operation link upon success. 
@jevonearth do you want me to wait for 3 confirmations on all examples? Takes a decent amount longer than just waiting for `op.confirmation()`
=> 300 - Update docs to support Carthagenet

packages/taquito-rpc/src/types.ts, packages/taquito/src/contract/contract.ts, packages/taquito/src/contract/prepare.ts, packages/taquito/src/operations/types.ts
- `parameters?` was incorrectly typed as `MichelsonV1Expression`.  New type is now `TransactionOperationHeader`.
- Removed the `rawParam` option, as this was not working anyway, and does not appear to be needed anyway.
- Removed some stray comments
Fix #312
=> fix(rpc): Apply correct type to parameters, remove rawParam option

example/package-lock.json, integration-tests/package-lock.json, package-lock.json, packages/taquito-http-utils/package-lock.json, packages/taquito-local-forging/package-lock.json, packages/taquito-michelson-encoder/package-lock.json, packages/taquito-react-components/package-lock.json, packages/taquito-remote-signer/package-lock.json, packages/taquito-rpc/package-lock.json, packages/taquito-signer/package-lock.json, packages/taquito-signer/package.json, packages/taquito-signer/src/import-key.ts, packages/taquito-signer/src/taquito-signer.ts, packages/taquito-signer/test/import-key.spec.ts, packages/taquito-tezbridge-signer/package-lock.json, packages/taquito-utils/package-lock.json, packages/taquito/package-lock.json, packages/taquito/package.json, packages/taquito/src/signer/interface.ts
Resolve cyclical dependency in @taquito/signer and fix dependencies from previous rebase in order to fix build issues.
The previous commit introduced a cyclical dependency. This commit should resolve that and reset the dependencies that were outdated from a rebase of master. The only issue is that in `import-key.ts` toolkit does not explicitly set a type.
```
export async function importKey(
toolkit: any,
privateKeyOrEmail: string,
passphrase?: string,
mnemonic?: string,
secret?: string
) {
```
Any ideas on how we can add a type to toolkit instead of `any`?
=> fix(signer): Fix merge issues from previous commit

packages/taquito-michelson-encoder/src/michelson-map.ts, packages/taquito-michelson-encoder/src/schema/storage.ts, packages/taquito-michelson-encoder/src/tokens/bigmap.ts, packages/taquito-michelson-encoder/src/tokens/map.ts, packages/taquito-rpc/src/utils/utils.ts, packages/taquito/src/contract/rpc-contract-provider.ts
User inputs that were instantiated from a different module instance of Taquito was not valid.
were rejected by the `instanceof` operator.
Implementing the solution described here: https://jakearchibald.com/2017/arrays-symbols-realms/#multiple-realms.
=> fix(taquito): Replace instanceof with static method to allow cross module type checks

integration-tests/config.ts, integration-tests/package.json, packages/taquito-http-utils/src/taquito-http-utils.ts, packages/taquito-remote-signer/src/taquito-remote-signer.ts, packages/taquito-signer/src/import-key.ts
- Add configuration options to run integration tests using InMemorySigner/faucet keys or RemoteSigner/ephemeral keys
- Allow users to specify custom HTTP headers via HttpRequestOptions
- Allow users to specify RemoteSignerConfig options
=> Integration tests use RemoteSigner/ephemeral keys, allow custom http headers

integration-tests/batch-api.spec.ts, integration-tests/contract-api-scenario.spec.ts, packages/taquito/src/contract/rpc-estimate-provider.ts, packages/taquito/test/contract/rpc-estimate-provider.spec.ts
Description of the issue:
Setting the storageLimit to 0 on an origination did not threw an error and did a dry run with the maximum storageLimit (60000). Also the actual operation sent by taquito
contained the explicit storageLimit instead of the that the user specified which lead to a failure on chain. So in this example the origination would have been reported as valid to the user but rejected by the chain.
- Ensure that we respect the explicit limit set by the user while estimating
- Add unit test coverage and integration test coverage for this issue
=> fix(estimator) Fix a bug where explicit limits were ignored by the estimator

packages/taquito-utils/src/taquito-utils.ts
Removing unused function `hexNonce` from `taquito-utils` package.
=> refactor(taquito-utils): remove unused function in taquito-utils

packages/taquito-signer/src/ec-key.ts, packages/taquito-signer/test/taquito-signer.spec.ts
When deriving the public key and ultimately the public key hash from a secret key, some keys need to be padded in order to produce a valid key length of 32 bytes.
Added additional tests in order to validate that this fix indeed addresses these cases.
=> fix(taquito-signer): Ensure public keys are padded correctly

docs/complex_parameters.md, docs/maps_bigmaps.md, docs/originate.md, packages/taquito-michelson-encoder/data/sample15.ts, packages/taquito-michelson-encoder/src/tokens/option.ts, packages/taquito-michelson-encoder/test/sample15.spec.ts, website/sidebars.json, website/src/theme/Playground/index.js
Fixed the Encode function of option.ts to remove optional value from the array of args when its value is null or undefined.
Added tests
=> Fix to encode schema properly when optional value is null

packages/taquito-tezbridge-wallet/src/taquito-tezbridge-wallet.ts
`getPKH` and `setHost` couldn't work properly as `tezbridge.request` is a promise and these two methods were not set as promises.
=> Turn getPKH() and setHost() into promises

docs/drain_account.md, website/sidebars.json, website/src/theme/Playground/index.js, website/src/theme/Playground/styles.module.css
Added examples on how to transfer all tokens from one account (implicit or originated) to another so that the source account balance is zero.
Fixed line breaks in the text displayed under live code examples.
=> Document how to drain/empty an account

packages/taquito-michelson-encoder/package.json
Closes #409 
Update dependencies for `@taquito/michelson-encoder` to include the RPC package, as the encoder depends on `MichelsonV1Expression` which is defined in the RPC pacakge.
=> fix(dep) Add dep to RPC for MichelsonV1Expression type

example/example-streamer.ts, packages/taquito/src/context.ts, packages/taquito/src/subscribe/observable-subscription.ts, packages/taquito/src/subscribe/polling-provider.ts, packages/taquito/test/subscribe/observable-subscription.spec.ts
currently, the observable in ObservableSubsription dies when getBlock rpc call fails. This change
makes it report the error via the error callback, but it continues to poll for new blocks
fix #430
- [NA] You have added unit tests
- [NA] You have added integration tests (if relevant/appropriate)
- [NA] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [NA] You have added or updated corresponding documentation
- [NA] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 
inclusion in the Release Notes for the next …
=> fix(subscribe): subscription should not die on rpc error

docs/rpc_nodes.md, example/contract-origination.ts, example/contract-origination2.ts, example/contract-origination3.ts, example/contract-schema.ts, example/example-activate.ts, example/example-node.ts, example/example-streamer.ts, example/pretty-print-contract.ts, example/scan-path-ledger.ts, integration-tests/ledger-signer-falling-tests.spec.ts, integration-tests/ledger-signer.spec.ts, packages/taquito/src/taquito.ts
For simplicity, the Tezos function added in the TezosToolkit (to replace the Tezos singleton after removing the default RPC URL) has been removed. So the only way to create a new instance will be :
`const tezos = new TezosToolkit('your_rpc');`
Fixed examples that were using this function.
=> Removed the Tezos function

docs/ledger_signer.md, docs/v7_breaking_changes.md, integration-tests/ledger-signer.spec.ts, packages/taquito-ledger-signer/src/taquito-ledger-signer.ts, packages/taquito-ledger-signer/test/taquito-ledger-signer.spec.ts
Replaced SECP256R1 with P256 to keep it more consistent with the ecosystem.
=> Replace SECP256R1 by P256 in the ledger-signer

docs/wallet_API.md, website/docusaurus.config.js, website/package-lock.json, website/package.json, website/src/theme/CodeBlock/index.js, website/src/theme/Playground/index.js
Added tezbridge plugin to docusaurus config to fix the Tezbridge wallet example.
Added the import for ThanosWallet.
Made the other examples use the taquito-beacon-wallet package otherwise it was using an ephemeral key to sign.
=> Fixed live code examples in the wallet documentation

integration-tests/config.ts
Support to set target RPC server addresses for integration tests has been added. 
If you have a local node, you can make tests run against that node by setting:
`export TEZOS_RPC_DELPHINET="http://localhos:8732"` prior to running integration tests.
=> chore: allow setting RPC node for tests via env

packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
- The active account in storage was used by default when requesting permission in Taquito. I removed it so the user can choose the account they want.
- Removed the permission property in the BeaconWallet class.
- Changed the removeAccount method for clearActiveAccount. This method allows to set the active account in the storage to undefined, so the user will be able to ask permission for another account.
=> Changes for beacon v2

packages/taquito/src/taquito.ts
When I removed the RPC URL, I added an optional context in the constructor of the Toolkit but it should not be accessible like that. This is a fix for it.
=> Removed context from TezosToolkit constructor

.github/workflows/main.yml
Carthagenet is no longer supported for the sending of operations. Reading data from the carthagenet period will continue to be supported.
=> chore: remove carthagenet integration tests from CI

docs/ledger_integration_test.md, integration-tests/README.md, integration-tests/ledger-signer-failing-tests.ts
__References in code, file names and documentation to "falling tests" have been changed to "failing tests."__
A typo in integration_tests/README.md is fixed.
=> Change falling tests to failing tests

packages/taquito/src/contract/prepare.ts, packages/taquito/src/operations/types.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts
Adds a mutez property (boolean) to createOriginationOperation as in createTransferOperation to make
things consistent.
Thanos wallet originates contracts after converting the balance from `ꜩ` to `uꜩ` twice. It is possible that other wallets also have this issue, but I've not tested them.
I could also submit a PR on Thanos repository to fix the issue, but I believe that this change is preferable.
If this PR gets merged, the Thanos team just needs to change their `mapOriginateParamsToWalletParams` method to this:
```js
async mapOriginateParamsToWalletParams(params: WalletOriginateParams) {
return { ...createOriginationOperation(params as any), mutez: true };
}
```
Adds a mutez property (boolean) to createOriginationOperation as in createTransferOperation to facilitate abstraction with …
=> feat(createoriginationoperation): adds a mutez property (boolean) to createOriginationOperation

docs/tzip12.md, integration-tests/tzip12-token-metadata.spec.ts, packages/taquito-tzip16/src/viewKind/michelson-storage-view.ts
Made a change to the Michelson views without parameter to match the behavior of TzComet.
Based on a discussion with Seb Mondet:
> the off-chain-view without parameter is a piece of code that transforms just the storage
=> Fix for Michelson view without param to match TZComet

integration-tests/contract-originate-contract-unpair.spec.ts, integration-tests/contract-originate-contract-with-sapling.spec.ts, integration-tests/edo-deploy-contract-having-ticket.spec.ts, integration-tests/wallet-originate-contract-unpair.spec.ts
Removed the faucet keys that needed to be used in the integration tests before updating the keygen to Taquito v8
=> Removed faucet key 

docs/wallet_API.md
There are some links in Taquito docs wallet-api doc that are pointing to -2.html instead of .html
This PR fixes them.
=> fix broken links in wallet-api doc

docs/wallet_API.md, integration-tests/contract-batch.spec.ts, integration-tests/wallet-batch.spec.ts, packages/taquito/src/contract/interface.ts, packages/taquito/src/contract/rpc-contract-provider.ts, packages/taquito/src/taquito.ts, packages/taquito/src/wallet/wallet.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts
#591 
The `batch` method on the `TezosToolkit` class has been deprecated and moved to the contract API.
Examples of use:
```
const batch = Tezos.contract
.batch()
.withTransfer({ to: 'tz1ZfrERcALBwmAqwonRXYVQBDT9BjNjBHJu', amount: 2 })
.withOrigination({
balance: '1',
code: codeContract,
storage: 0
});
const op = await batch.send();
```
```
const op = await Tezos.contract.batch([
{
kind: OpKind.TRANSACTION,
to: 'tz1ZfrERcALBwmAqwonRXYVQBDT9BjNjBHJu',
amount: 2
},
{
kind: OpKind.ORIGINATION,
balance: "1",
code: codeContract,
storage: 0,
}
])
.send();
```
At the same time, `wallet.batch` method has been refactored so it can be used the same way as with the contract API.
Example:
```
const batch = Tezos.wallet
.batch()
.withTransfer({ to: 'tz1ZfrERcALBwmAqwonRXYVQBDT9BjNjBHJu', amount: 2 }) …
```
=> Refactor batch API

docs/quick_start.md
As we are on version 8 now, we no longer need a warning in the documentation about breaking changes introduced in v7.
=> update taquito docs quick-start page to remove v7 breaking changes warning

integration-tests/contract-batch.spec.ts, integration-tests/contract-tx-wait-2-confirmations.spec.ts, integration-tests/wallet-no-annotations-call-by-index.spec.ts, integration-tests/wallet-originate-contract-unpair.spec.ts, integration-tests/wallet-originate-vote-contract.spec.ts, integration-tests/wallet-unit-as-param.spec.ts
There are still integration tests for Taquito failing in CI/CD. These additional retries should help make MRs get through the pipelines more easily.
=> More integration tests need retries

docs/batch-api.md
I updated the docs for the Batch API to reflect recent changes.
However, I haven't been able to test them as using `Tezos.wallet.batch().with...` raises an error with the latest Taquito version available (`Expected 1 arguments, but got 0`). A new version should be made available to download in order to test the changes.
=> Updated docs to show batch method on Wallet and Contract

integration-tests/contract-simple-delegation.spec.ts, packages/taquito/src/contract/prepare.ts, packages/taquito/src/operations/operation-emitter.ts
We need to be able to delegate to a tz address as well as to a SG1 address on Falphanet.
I made a modification to add {version: '1'} to the operation if the delegate is a SG1 address instead of if the protocol is PsrsRVg1.
=> Keep compatibility to delegate to a tz address

.github/workflows/main.yml, docs/rpc_nodes.md
The RPC nodes list in Taquito docs at https://tezostaquito.io/docs/rpc_nodes is out of date
drop the Delphi nodes and add ECAD florencenet node.
Close #694
=> Update rpc nodes list in Taquito online docs

packages/taquito-michelson-encoder/data/sample19_timestamp_ticket.ts, packages/taquito-michelson-encoder/src/tokens/ticket.ts, packages/taquito-michelson-encoder/test/sample18_nat_ticket.spec.ts, packages/taquito-michelson-encoder/test/sample19_timestamp_ticket.spec.ts, packages/taquito-michelson-encoder/test/tokens/ticket.spec.ts
#686
The value stored in a Ticket can be of any comparable Michelson type, and now you can read all Ticket values using Taquito!
=> Support all token types for the property value of a ticket

integration-tests/call-get-delegate-when-no-delegate.spec.ts, packages/taquito-rpc/src/taquito-rpc.ts
#556 
When calling the `getDelegate()` method on an account that is not delegated, Taquito will now return `null` instead of throwing a HTTP 404 exception.  This is a breaking change for users who were handling the undelegated condition with a `catch`
=> Return null when an account has no delegate 

docs/rpc_nodes.md
The architecture consists of a nginx load-balancer and two Tezos bare-metal nodes. We are using a whitelist approach to access the node so that dangerous calls are prevented. If a rpc required by developers is currently missing, we are very approachable and happy to add the respective rpc to the whitelist. 
https://letzbake.com/
https://t.me/cryptodad77
=> Added Teznode to list of community-run nodes

docs/maps_bigmaps.md, integration-tests/contract-fetch-multiple-big-map-keys.spec.ts, integration-tests/contract-pair-as-key.spec.ts, packages/taquito-michelson-encoder/src/schema/storage.ts, packages/taquito-michelson-encoder/src/taquito-michelson-encoder.ts, packages/taquito-michelson-encoder/src/tokens/comparable/int.ts, packages/taquito-michelson-encoder/src/tokens/comparable/mutez.ts, packages/taquito-michelson-encoder/src/tokens/comparable/nat.ts, packages/taquito-michelson-encoder/src/tokens/token.ts, packages/taquito-michelson-encoder/test/tokens/int.spec.ts, packages/taquito-michelson-encoder/test/tokens/mutez.spec.ts, packages/taquito-michelson-encoder/test/tokens/nat.spec.ts, packages/taquito-rpc/src/types.ts, packages/taquito/src/contract/big-map.ts, packages/taquito/src/contract/interface.ts, packages/taquito/src/contract/rpc-contract-provider.ts, packages/taquito/test/contract/big-map.spec.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts
Replace #513 
Breaking change for `BigMapAbstraction.getMultipleValues()` and `RpcContractProvider.getBigMapKeysByID()` that will return a `MichelsonMap` instead of an object to support keys of type object (michelson pair)
=> Allows to fetch bigmap with a key of type string, number or object

docs/upgrading_guide.md, docs/version.md, website/sidebars.json
#673 
Changed page `Upgrading to v7/delphi` to `Upgrading Guide` and added instructions for v8 and v9
=> Upgrading v9

integration-tests/contract-batch-high-number-of-operations.spec.ts
With the changes in galpha2net, the estimation is not working with a batch having a high number of operations. 
Temporarily fix is to explicitly specify the gasLimit instead of relying on the estimate.
=> Added a test cases with 150 operations in a batch

packages/taquito-rpc/src/opkind.ts, packages/taquito-rpc/src/types.ts, packages/taquito-rpc/test/taquito-rpc.spec.ts
=> Added big_map_diff, lazy_storage_diff properties and failing_noop operation to RPC types

packages/taquito-signer/src/ec-key.ts, packages/taquito-signer/test/taquito-signer.spec.ts
We were looking at the byte at position 31 of the "y" coordinate to determine which prefix to use (3
if odd or 2 if even) when deriving the public key. The bug happened in cases where the "y"
coordinate was shorter than 32 bytes. The value at position 31 was undefined, so the prefix "2" was
always used enven if the "y" coordinate was odd.
fix #848
=> fix(taquito-signer): ensure correct byte is used to determine parity

website/docusaurus.config.js
the update for the version of Taquito Docs was set to v9.1, it should have been v9.1.0  so this corrects it :)
=> correct  Taquito docs version number update

integration-tests/contract-batch-high-number-of-operations.spec.ts, packages/taquito/src/contract/rpc-estimate-provider.ts, packages/taquito/test/contract/rpc-estimate-provider.spec.ts
Fix needed for Granada where the total gasLimit of a batch operation can not exceed the
hard_gas_limit_per_block constant when doing the estimation of the operation
fix #922
=> fix(batch-estimation): estimation of batch operation broken by Granada

website/docusaurus.config.js
A TypeScript library suite made available as set of npm packages
corrected to
A TypeScript library suite made available as a set of npm packages
This Pr will close #974
=> corrected typo in website

.github/workflows/codeql-analysis.yml
Signed-off-by: Gino Imbrailo <ginoimbrailo@gmail.com>
After redeploying the self-hosted GitHub runners for Taquito we would like the CodeQL action to run on self-hosted runners again.
=> Draft: chore: changed codeql ci job to self-hosted

integration-tests/contract-empty-implicit-account-into-new-implicit-account.spec.ts, packages/taquito/src/contract/estimate.ts
This is a temporary fix. The consumed_gas returned by the RPC 
`helpers/scripts/run_operation` seems too low in this particular case. Thus the `gasLimit` and the `fee` returned by the estimate are too low. See https://gitlab.com/tezos/tezos/-/issues/1754
=> fix-test-contract-empty-implicit-account-into-a-new-implicit-account.spec.ts

integration-tests/contract-with-key-collections.spec.ts, integration-tests/data/contract-with-key-collections.ts, packages/taquito-michelson-encoder/src/tokens/key.ts, packages/taquito-michelson-encoder/test/tokens/key.spec.ts, packages/taquito-michelson-encoder/test/tokens/map.spec.ts
Fixed key sorting in literal sets and maps when these collections have mixed key types.
Before this fix, we couldn't send key sets containing multiple key types (Ed25519, Secp256k1, P256) to RPC, e.g.
```json
[
"edpkvS5QFv7KRGfa3b87gg9DBpxSm3NpSwnjhUjNBQrRUUR66F7C9g",
"sppk7aVdgAmezMCRTcHciVkVZoGNnhSdKEYcn5pYaqt4PvLjgFbLRxo",
"p2pk65shUHKhx7zUSF7e8KZ2inmQ5aMS4jRBUmK6aCis4oaHoiWPXoT"
]
```
If we try to use this set we'll get an error `michelson_v1.unordered_set_literal`, as the michelson encoder sorts the set using the default compare method, method of the `ComparableToken` class. In other words, the encoder sorts the set using alphabetic sorting.
Unfortunately, I've found no description of the …
=> Key ordering

packages/taquito/src/contract/rpc-estimate-provider.ts, packages/taquito/src/parser/michel-codec-parser.ts
Small optimization.
There were two distinct calls to the RPC constants endpoint in the `RPCEstimateProvider` class: one in the `getAccountLimits` method and the other in the `prepareEstimate` method.
They have been combined into one call.
=> perf(EstimateProvider) combine 2 calls to rpc.getConstants into 1

packages/taquito-tzip16/src/handlers/ipfs-handler.ts, packages/taquito-tzip16/test/handlers/ipfs-handler.spec.ts
`httpBackend` of IpfsHttpHandler has been updated to be a public field.
https://github.com/ecadlabs/taquito/issues/1092
=> Allow to set HttpBackend on IpfsHttpHandler (#1092)

docs/metadata-tzip16.md
the IPFS live code example for metadata needs a new contract.
closes issue #1190
=> repair the docs ipfs  example

integration-tests/rpc-get-protocol-constants.spec.ts
Closes #1216
Update `rpcUrl` constant to point to the dedicated Tezos `archive` node endpoint  `https://mainnet-archive.api.tez.ie`
=> Use dedicated endpoint to reach Tezos mainnet archive nodes

packages/taquito-michel-codec/src/macros.ts, packages/taquito-michel-codec/src/michelson-typecheck.ts, packages/taquito-michel-codec/src/michelson-types.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts
I changed the logic of the if/else statements where we act differently according to the protocol hash.
The behavior regarding macro expansion is different since the Edo protocol. There were checks in the codebase (using ProtoGreaterOfEqual) to see if the protocol used was higher than Edo and if so to apply the "Edo Since" behavior. However, if a user was using Taquito with a new protocol that is not yet supported (not part of the Protocol enum), the default behavior to expand macro was the "before Edo". I made a change so the  "Edo Since" behavior is used by default unless the protocol used is inferior to Edo (which is less likely).
=> Refactor(michel-codec) use newest protocol behaviour by default

integration-tests/contract-estimation-tests.spec.ts, packages/taquito/src/operations/operation-emitter.ts
When preparing an operation the block was set to head. In the Ithaca protocol, the block needs to be
`HEAD~2`. Setting the branch field to `HEAD` or `HEAD~1` may result in the operation not being included
because it will not be anchored on a block belonging to the chain. (The blocks at the current and
previous levels are not necessary final.)
fix #1230
=> fix(ithacanet): block needs to be HEAD~2

packages/taquito/src/contract/contract.ts, packages/taquito/test/contract/contractView.spec.ts
Use ExtractSchema instead of ExtractSignature in the ContactAbstraction to determine if an entry
point is a lambda view. For some particular contracts having nested pair and option types,
ExtractSignature leads to memory issues by generating all possible signatures.
fix #1270
=> fix(contractabstraction): Getting ContractAbstraction for large contracts takes too much resources (memory, time)

packages/taquito-michelson-encoder/src/tokens/comparable/nat.ts, packages/taquito-michelson-encoder/test/tokens/map.spec.ts
Fixed a bug where decoding MichelsonMap keys of type nat would return a string instead of a
BigNumber.
fix #1140
=> fix(michelsonmap): natToken.ToKey should return a BigNumber

docs/ledger_signer.md, website/package-lock.json, website/package.json, website/plugins/webpack5plugin/index.js, website/src/theme/CodeBlock/index.js, website/yarn.lock
"@ledgerhq/hw-transport-u2f" expires in February and has been replaced by
"@ledgerhq/hw-transport-webhid" in the live code example
fix #1266
=> docs(website ledger documentation): replace utf transport with web-hid

packages/taquito-signer/package-lock.json, packages/taquito-signer/package.json, packages/taquito-signer/src/mnemonicToSeedSync.ts, packages/taquito-signer/src/taquito-signer.ts
Bip 39 had unneeded translation files increasing the bundle size.
fix #1110
=> fix(signer): removed bip39 dependency

.github/workflows/algolia.yml, .github/workflows/codeql-analysis.yml, .github/workflows/deploy_edge.yml, .github/workflows/deploy_website.yml, .github/workflows/main.yml, .github/workflows/preview_website.yml
Closes #1342 
When working on PR or when merging to `master` we should always make sure to run pipeline against the latest code.
Currently when we push new commits to a PR the new pipelines for the latest code are queued up and need to wait for previous pipelines to complete.
By limiting workflow concurrency old pipelines will be cancel automatically when a newer commit is pushed to a PR.
Testing this changes to show that when new commits are pushed old pipelines are automatically cancelled.
=> Limit GH Action workflows concurrency

.github/workflows/algolia.yml, .github/workflows/deploy_edge.yml, .github/workflows/main.yml
We've been running Taquito integration tests with our self-hosted runners for some times now; however due to our current infrastructure we can't scale self-hosted runner on demand the way we would like to. Furthermore the operational cost for maintaining the runners is starting to put some weight on the SRE team.
As Github offers unlimited minutes when using runners for public repositories I suggest we switch all our CI/CD jobs to public runners. Since we make use of endpoint and services internal to our network I'm using the [tailscale/github-action](https://github.com/tailscale/github-action/actions) to authenticate the runner to our internal network. Worth noting that I configured Tailscale ACLs to restrict communication only to required services.  
All pipelines succeeded …
=> Run Taquito integration tests from public GH runners

.github/workflows/algolia.yml, .github/workflows/codeql-analysis.yml, .github/workflows/deploy_edge.yml, .github/workflows/deploy_website.yml, .github/workflows/main.yml, .github/workflows/preview_website.yml
Closes #1342 
@roxaneletourneau pointed out that we should keep concurrency enabled for pushes to the `master` branch to detect easily commits causing problems to the pipelines.
Conditionals aren't natively supported in `concurrency` blocks however I'm using a workaround by using the OR operator found in https://github.community/t/concurrency-cancel-in-progress-but-not-when-ref-is-master/194707/4?u=danielelisi
The trick is with the expression `${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}`  since commits to `master` branch will always create separate concurrency groups based on the ever increasing `github.run_number` variable 
I can't really test this change without committing to master so just code review and have faith pls :angel:
=> Don't limit concurrency for pipelines triggered on master branch

packages/taquito/src/context.ts, packages/taquito/test/context.spec.ts
Fixes Bug: https://github.com/ecadlabs/taquito/issues/1379
---
FIX Wallet Originated Contract methods usage should work as expected
=> Context clone missing some fields

code-of-conduct.md
Wholesale replacement of previous Contributor Covenant v.1.4 Code of Conduct with new v.2.1 better suited to moderation of community spaces such as Discord (see source at https://www.contributor-covenant.org/version/2/1/code_of_conduct/).
This change also replaces the reporting contacts with new email abuse@ecadlabs.com and administrators/moderators in official community channels. Previous email address and keybase contacts no longer active.
=> update Code of Conduct

integration-tests/contract-call-with-xtz-amount.spec.ts, integration-tests/contract-estimation-tests.spec.ts, integration-tests/contract-originate-contract-with-single-sapling-state.spec.ts, integration-tests/contract-sub-mutez.spec.ts, integration-tests/contract-unit-as-param.spec.ts, integration-tests/rpc-nodes.spec.ts, integration-tests/wallet-unit-as-param.spec.ts
Step two in migrating integration tests to Ithacanet2
CLOSE #1376
=> cleanup tests that do not require skipithacanet anymore

packages/taquito/src/context.ts, packages/taquito/src/forger/taquito-local-forger.ts, packages/taquito/src/parser/michel-codec-parser.ts, packages/taquito/src/taquito.ts, packages/taquito/test/batch/rpc-batch-provider.spec.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts, packages/taquito/test/contract/rpc-estimate-provider.spec.ts, packages/taquito/test/forger/taquito-local-forger.spec.ts, packages/taquito/test/taquito.spec.ts, packages/taquito/test/tz/rpc-tz-provider.spec.ts
Implemented a new class named TaquitoLocalForger which act as a wrapper around the LocalForger in
order to fetch and pass the protocol hash on instantiation.
This change is required in preparation for Ithaca support, where some operation schema has changed (ie endorsement), the protocol hash is passed to the constructor of the LocalForger in order to select the right encoder, decoder.
=> refactor(taquito): pass protocol hash to LocalForger

docs/estimate.md, packages/taquito/src/context.ts, packages/taquito/src/estimate/error.ts, packages/taquito/src/estimate/index.ts, packages/taquito/src/estimate/rpc-estimate-provider.ts, packages/taquito/src/operations/operation-emitter.ts, packages/taquito/test/estimate/rpc-estimate-provider.spec.ts
Estimation is done with the configured signer. If there is no configured signer, estimation is done
using the public key hash of the configured wallet. Taquito does not have access to the public key
of the wallet (only the pkh), so won't estimate reveal operation. If the account is unrevealed, an
exception is throwned.
re #1387
=> feat(estimate): fix estimate to work with wallet

packages/taquito-http-utils/src/taquito-http-utils.ts
#1091 
- Simple change to expose the full error object using the existing HttpRequestFailed error object
=> made use of HttpRequestFailed error to expose generic error details

.github/workflows/deploy_edge.yml, .github/workflows/preview_website.yml
Currently, Taquito PRs get polluted by automated comments every time a new commit is pushed.
Instead of creating new comments for Netlify previews and NPM package deployments we can update the existing ones with the latest information.
| Before | After |
| --- | --- |
| ![Screenshot from 2022-04-09 00-13-42](https://user-images.githubusercontent.com/22307776/162540705-55a41f66-0ae7-4315-9fc4-8c4ffc4d08ee.png) | ![Screenshot from 2022-04-09 02-07-14](https://user-images.githubusercontent.com/22307776/162548266-0559e703-9c7c-444e-a08a-e8646209cc78.png)
|
=> [ci] Sticky comments for Pull Requests

packages/taquito-contracts-library/src/rpc-wrapper.ts, packages/taquito-contracts-library/src/taquito-contracts-library.ts, packages/taquito-contracts-library/test/rpc-wrapper.spec.ts, packages/taquito/src/contract/rpc-contract-provider.ts, packages/taquito/src/read-provider/rpc-read-adapter.ts, packages/taquito/test/contract/contract-abstraction-composer.spec.ts, packages/taquito/test/contract/contractView.spec.ts, packages/taquito/test/contract/lambda-view-class.spec.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts, packages/taquito/test/read-provider/rpc-read-adapter.spec.ts, packages/taquito/test/wallet/contract-abstraction-composer-wallet.spec.ts
Avoid doing POST call to fetch contract script with the RPC
fix #1532
=> perf(rpc): use getContract to fetch script

packages/taquito-utils/src/constants.ts, packages/taquito-utils/src/validators.ts, packages/taquito-utils/test/validators.spec.ts
I just authorized "txr1" rollup addresses to the list of valid contract prefixes.
rollups on Mondaynet are protocol smart contract that acts like any user smart contract, taquito should allow to forge a Contract object from a rollup contract address
This is a minor change but it is blocking my development on a dapp for the Tezos rollups
=> add support for transaction rollup contract addresses

.github/workflows/main.yml, .github/workflows/mondaynet.yml
The Tailscale action is still using `v1.14.2` and should be updated to use a newer version `v1.22.2`
=> Updated tailscale version

.eslintrc.json, packages/taquito-contracts-library/src/rpc-wrapper.ts, packages/taquito-local-forging/src/proto12-ithaca/constants.ts, packages/taquito-michel-codec/src/michelson-typecheck.ts, packages/taquito-michel-codec/test/contracts_010.spec.ts, packages/taquito-remote-signer/test/taquito-remote-signer.spec.ts, packages/taquito-rpc/src/rpc-client-interface.ts, packages/taquito-rpc/src/rpc-client-modules/rpc-cache.ts, packages/taquito-rpc/test/rpc-cache.spec.ts, packages/taquito-tezbridge-wallet/src/taquito-tezbridge-wallet.ts, packages/taquito-utils/test/taquito-utils.spec.ts, packages/taquito/patch.js, packages/taquito/src/contract/contract.ts, packages/taquito/src/wallet/wallet.ts, packages/taquito/test/read-provider/rpc-read-adapter.spec.ts, packages/taquito/webpack.config.js
linter throw error if contains unused variables / uses require() instead of import
ignores arguments and variables that start with `_`
only one disable comment for require() in patch.js
=> update no unused vars, strict

integration-tests/contract-estimation-tests.spec.ts
for the contract estimation integration tests for Jakarta, some of the tests' expected values need to be updated.
4 tests each required update to  (estimate.consumedMilligas, e.g.
expect(estimate.consumedMilligas).toEqual(4974505);
CLOSE #1588
=> updated the expected estimations

integration-tests/contract-estimation-tests.spec.ts
The estimated contract value tests for jakartanet are failing. The values asserted for these tests can drift around during the early phases of an upcoming protocol. This is an adjustment to get the cicd passing again.
close #1588
=> update the updated estimated values

integration-tests/rpc-nodes.spec.ts
Close #1633
I split the failing test up into two to run on Jakartanet and ithacanet and the other to run on mondaynet but with a different expectation.
This will get the cicd to pass again, but we still need to understand why the test fails on mondaynet.
=> split failed test into two node

docs/on_chain_views.md
Close #1610 
the contract addresses were reversed in the example, leading to error{}
=> corrected failing live code example for wallet

docs/quick_start.md
links to BCD and to Ligo were incorrect for a contract example in docs quickstart
Closes #1566
=> corrected links to BCD and Ligo in quickstart doc

integration-tests/contract-with-txr1-address.spec.ts, integration-tests/data/contract-txr1-address.ts, packages/taquito-michelson-encoder/src/tokens/comparable/address.ts, packages/taquito-michelson-encoder/src/tokens/contract.ts, packages/taquito-michelson-encoder/test/tokens/address.spec.ts, packages/taquito-michelson-encoder/test/tokens/contract.spec.ts, packages/taquito-michelson-encoder/test/tokens/tx_rollup_l2_address.spec.ts, packages/taquito-utils/src/taquito-utils.ts, packages/taquito-utils/test/taquito-utils.spec.ts, website/package-lock.json
adaptation for Address Token to accept and properly manage txr1 addresses from tx rollup transactions 
added integration tests for jakartanet and unit tests 
=> 1641 txr1 encoder addition to AddressToken Class

.github/workflows/mondaynet.yml, .github/workflows/tezedge.yml
Relates to #1446
- Run integration tests against Tezedge node on a schedule every Tuesday just like Mondaynet tests
- Run Tezedge and Mondaynet tests selectively only when we include their name in a branch name. for example `update_mondaynet_tests` or `fix_tests_tezedge` 
- Avoid running mondaynet tests against each commit to avoid pipeline failures caused by mondaynet tests like the screenshot below
=> [ci] Run integration tests against tezedge node every tuesday

.github/workflows/main.yml
Taquito integration test pipeline cancels the entire job if one of the job fails. This shouldn't happen since the 2 testnets should test separately
This PR fixes this behaviour
=> [ci] Fix pipeline failures with integration tests

integration-tests/contract-empty-implicit-account-into-new-implicit-account.spec.ts, integration-tests/contract-estimation-tests.spec.ts
Close #1771 
This is a redo of this issue as the previous PR ran into too many rebase conflicts.
updates the tet for K by removing the now unneeded gas fee offset from the implicit account draining operation
=> Remove unnecessary gas fee offset from integration test

docs/sapling.md, integration-tests/sapling-batched-transactions.spec.ts, integration-tests/sapling-transactions.spec.ts, packages/taquito-sapling/src/taquito-sapling.ts, packages/taquito-tzip16/test/viewKind/michelson-storage-view.spec.ts, packages/taquito/src/context.ts, packages/taquito/src/read-provider/rpc-read-adapter.ts, packages/taquito/src/taquito.ts, packages/taquito/test/contract/contract-abstraction-composer.spec.ts, packages/taquito/test/contract/contract-on-chain-view.spec.ts, packages/taquito/test/contract/lambda-view-class.spec.ts, packages/taquito/test/read-provider/rpc-read-adapter.spec.ts, packages/taquito/test/wallet/contract-abstraction-composer-wallet.spec.ts
Takes a rpcClient in the constructor instead of a context. Context is an internal class that should
not be available to the users.
BREAKING CHANGE: RpcReadAdapter needs a RpcClient in the constructor
=> refactor(read-adapter): remove the context from the constructor

docs/sapling.md, docs/sapling_in_memory_viewing_key.md, integration-tests/sapling-batched-transactions.spec.ts, integration-tests/sapling-transactions-contract-with-multiple-sapling-states.spec.ts, integration-tests/sapling-transactions-contract-with-single-state.spec.ts, integration-tests/sapling-transactions-proof-using-proving-key.spec.ts, packages/taquito-sapling/src/sapling-forger/sapling-forger.ts, packages/taquito-sapling/src/sapling-keys/helpers.ts, packages/taquito-sapling/src/sapling-keys/in-memory-proving-key.ts, packages/taquito-sapling/src/sapling-keys/in-memory-spending-key.ts, packages/taquito-sapling/src/sapling-keys/in-memory-viewing-key.ts, packages/taquito-sapling/src/sapling-module-wrapper.ts, packages/taquito-sapling/src/sapling-tx-builder/sapling-transactions-builder.ts, packages/taquito-sapling/src/taquito-sapling.ts, packages/taquito-sapling/src/types.ts, packages/taquito-sapling/test/data/sapling_test_data.ts, packages/taquito-sapling/test/sapling-keys/in-memory-proving-key.spec.ts, packages/taquito-sapling/test/sapling-keys/in-memory-spending-key.spec.ts, packages/taquito-sapling/test/sapling-tx-builder/sapling-module-wrapper.spec.ts, packages/taquito-sapling/test/sapling-tx-builder/sapling-transaction-builder.spec.ts, packages/taquito-sapling/test/taquito-sapling.spec.ts, website/src/theme/CodeBlock/index.js
Implemented an InMemorySpendingKey class that allows producing proofa independently from the
spending key. Did some refactor and renaming also.
BREAKING CHANGE: The first parameter of the SaplingToolkit class changed for an object accepting an
optional InMemorySpendingKey
=> feat(sapling): support proof generation from provingkey

packages/taquito/src/estimate/rpc-estimate-provider.ts, packages/taquito/test/contract/helper.ts, packages/taquito/test/estimate/rpc-estimate-provider.spec.ts
In Kathmandu, the field consumed_gas has been removed. The estimate-provider needs to use the
consumed_milligas property.
re #1769 (part 1)
=> fix(estimate): replace consumed_gas with consumed_milligas

integration-tests/local-forging.spec.ts, packages/taquito-local-forging/src/constants.ts, packages/taquito-local-forging/test/allTestsCases.ts, packages/taquito-local-forging/test/data/code_with_emit.ts, packages/taquito-local-forging/test/taquito-local-forging.spec.ts
Added support to forge/parse the new EMIT instruction in Kathmandu
re #1742
=> feat(local-forging): support EMIT instruction

integration-tests/config.ts, integration-tests/rpc-nodes.spec.ts
Close 1784
removing the hardcoded address from the tests
=> reconfigure rpc node tests to use config variable for tx rollup address

integration-tests/contract-batch.spec.ts, integration-tests/contract-register-global-constant.spec.ts, integration-tests/contract-simple-delegation.spec.ts, integration-tests/contract-simple-origination.spec.ts, integration-tests/contract-simple-reveal.spec.ts, integration-tests/contract-tx-rollup-batch-operation.spec.ts, integration-tests/contract-tx-wait-2-confirmations.spec.ts, packages/taquito-michelson-encoder/src/schema/model.ts, packages/taquito/src/operations/batch-operation.ts, packages/taquito/src/operations/delegate-operation.ts, packages/taquito/src/operations/origination-operation.ts, packages/taquito/src/operations/register-global-constant-operation.ts, packages/taquito/src/operations/reveal-operation.ts, packages/taquito/src/operations/transaction-operation.ts, packages/taquito/src/operations/transfer-ticket-operation.ts, packages/taquito/src/operations/tx-rollup-batch-operation.ts, packages/taquito/src/operations/tx-rollup-origination-operation.ts, packages/taquito/test/contract/helper.ts, packages/taquito/test/data/batch-results.ts, packages/taquito/test/helpers.ts, packages/taquito/test/operations/batch-operation.spec.ts, packages/taquito/test/operations/delegation-operation.spec.ts, packages/taquito/test/operations/origination-operation.spec.ts, packages/taquito/test/operations/register-global-constant.spec.ts, packages/taquito/test/operations/reveal-operation.spec.ts, packages/taquito/test/operations/transaction-operation.spec.ts, packages/taquito/test/operations/transfer-ticket-operation.spec.ts, packages/taquito/test/operations/tx-rollup-origination-operation.spec.ts, packages/taquito/test/operations/tx-rollup-submit-batch.spec.ts
In kathmandu, the property consumed_gas is removed from the RPC responses in favor or
consumed_milligas. Added a getConsumedMilliGas getter on every Operation class from the Contract
API. Adjust the getConsumedGas getter to use the consumed_milligas divided by 1000 and rounded up. Fix
a small bug in the DelegateOperation class.
re #1769 (part 2)
=> fix(contract operation): replace consumed_gas with consumed_milligas

packages/taquito/src/constants.ts, packages/taquito/src/wallet/receipt.ts, packages/taquito/test/wallet/data.ts, packages/taquito/test/wallet/operation.spec.ts
In kathmandu, the property consumed_gas is removed from the RPC responses in favor of
consumed_milligas. Added a totalMilliGas property to the receipt and totalGas is now the total
milliGas divided by 1000 and roundedup.
re #1769
=> fix(wallet receipt): replace consumed_gas with consumed_milligas

docs/batch-api.md, integration-tests/injecting-multiple-manager-operations-in-a-block.spec.ts
Added a test showing the expected error message if we try to inject multiple maganer operations in
the same block
re #1748
=> test(integration test): 1 manager operation per manager per block

docs/batch-api.md, integration-tests/injecting-multiple-manager-operations-in-a-block.spec.ts, packages/taquito/src/injector/helper.ts, packages/taquito/src/injector/rpc-injector.ts
Override "Error while applying operation opHash: Only one manager operation per manager per block
allowed (found opHash2 with Xtez fee. You may want to use --replace to provide adequate fee and
replace it)." for "Error while applying operation opHash: Only one manager operation per manager per
block allowed (found opHash2 with Xtez fee)."
=> style(injector): remove unwanted error message related to tezos-client

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
Recent CodeQL GH Action runs are throwing errors caused by Github runners running out of memory. An example of the error is present in the snippet below.
https://github.com/ecadlabs/taquito/actions/runs/3003313388/jobs/4829799996
```
Error: 9-07 11:49:09] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220825/x64/codeql/javascript/tools/autobuild.sh])
A fatal error occurred: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220825/x64/codeql/javascript/tools/autobuild.sh]
Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220825/x64/codeql/codeql' failed with exit code 2
Error: The process …
```
=> Tweak configuration for CodeQL analysis

packages/taquito/src/estimate/rpc-estimate-provider.ts, packages/taquito/test/estimate/rpc-estimate-provider.spec.ts
adds two tests for malformed tz1 and kt1 to test rejection
=> Transfer ticket improvements

integration-tests/contract-michelson-origination.spec.ts, packages/taquito/src/contract/errors.ts, packages/taquito/src/contract/prepare.ts, packages/taquito/src/operations/types.ts
allow balance to be entered as a number or string. add tests. and error cases
=> 1795 contract balance flexibility

docs/complex_parameters.md, docs/inmemory_signer.md, docs/quick_start.md, docs/smartcontracts.md, integration-tests/contract-register-delegate.spec.ts, integration-tests/contract-set-delegate-auto-estimate.spec.ts, integration-tests/contract-simple-delegation.spec.ts, integration-tests/wallet-register-delegate.spec.ts, integration-tests/wallet-set-delegate-auto-estimate.spec.ts, packages/taquito-signer/README.md, packages/taquito-signer/src/import-key.ts, website/src/theme/Playground/index.js, website/versioned_docs/version-14.0.0/complex_parameters.md, website/versioned_docs/version-14.0.0/inmemory_signer.md, website/versioned_docs/version-14.0.0/quick_start.md, website/versioned_docs/version-14.0.0/smartcontracts.md
Since August 2022, JSON faucet are no longer available
fix #1872
=> docs(faucet): remove usage of JSON faucet in the documentation

integration-tests/contract-handling-missed-blocks.spec.ts, integration-tests/wallet-handling-missed-blocks.spec.ts, package-lock.json, packages/taquito-beacon-wallet/package-lock.json, packages/taquito/src/operations/operations.ts, packages/taquito/src/wallet/operation.ts, packages/taquito/test/wallet/data.ts, packages/taquito/test/wallet/operation.spec.ts, website/package-lock.json, website/yarn.lock, yarn.lock
During the confirmation of an operation (step where we poll on the head block until the injected operation is found), Taquito was throwing an error `MissedBlockDuringConfirmationError` when blocks were skipped. 
Made a change to fetch the skipped blocks and verify if the operation is inside those instead of throwing an error. The polling resumes normally after fetching those blocks if the operation is not found. 
re #1783
=> fix(wallet and contract APIs): fetch missed blocks during operation confirmation

integration-tests/config.ts, integration-tests/contract-confirmation-timeout.spec.ts, integration-tests/contract-handling-missed-blocks.spec.ts, integration-tests/polling-subscribe-provider.spec.ts, integration-tests/wallet-confirmation-timeout.spec.ts, packages/taquito/src/operations/operations.ts, packages/taquito/src/wallet/operation-factory.ts, packages/taquito/src/wallet/operation.ts
The timeout was not taken into consideration on both the contract and wallet API when confirming the operations. In cases where an operation was not found, our integration tests would never end instead of throwing a timeout error.
fix #2006
=> fix(confirmationPollingTimeoutSecond): fix for contract/wallet API

.github/workflows/mondaynet.yml
Send a slack notification to the `taquito_integration_tests` Slack channel with the result of the scheduled integration test ran against Mondaynet network and Tezedge nodes on Ithacanet
Triggered the workflow and confirmed we are receiving the Slack notification
=> [ci] Send Slack notification for Mondaynet integration tests result

integration-tests/contract-security-non-existent-KT-address.spec.ts
To test:
1. Start local, sandboxed Octez node with RPC endpoint `http://127.0.0.1:18731`.
2. Run `TEZOS_RPC_MONDAYNET=http://127.0.0.1:18731 npm run "test:mondaynet-secret-key" "contract-security-non-existent-KT-address.spec.ts"`
3. The test should work with this fix, and will fail without it as described in #2091
=> contract-security-non-existent-KT-address: use rpc (#2091)

integration-tests/contract-increase-paid-storage-operation.spec.ts, integration-tests/rpc-nodes.spec.ts, packages/taquito-contracts-library/src/rpc-wrapper.ts, packages/taquito-rpc/src/rpc-client-interface.ts, packages/taquito-rpc/src/rpc-client-modules/rpc-cache.ts, packages/taquito-rpc/src/taquito-rpc.ts, packages/taquito-rpc/test/rpc-cache.spec.ts, packages/taquito-rpc/test/taquito-rpc.spec.ts
closes #2076 
- Added new endpoints for `used_space` and `paid_space` in storage
- Updated integration tests
=> added new rpc endpoints and updated tests

integration-tests/contract-call-with-xtz-amount.spec.ts, integration-tests/contract-unit-as-param.spec.ts, integration-tests/wallet-unit-as-param.spec.ts, packages/taquito-local-forging/src/constants.ts, packages/taquito-local-forging/src/proto14-kathmandu/codec-proto14.ts, packages/taquito-local-forging/src/proto14-kathmandu/constants-proto14.ts, packages/taquito-local-forging/test/codec.spec.ts
In lima protocol, the %deposit entrypoint is now represented by 0x05
fix #2158
https://gitlab.com/tezos/tezos/-/blob/master/src/proto_015_PtLimaPt/lib_protocol/entrypoint_repr.ml#L214
=> fix(local-forging): fix encoding for deposit entrypoint

apps/taquito-test-dapp/README.md
Add missing steps to test dapp docs
The steps in these updated instructions were followed exactly. I also deviated by skipping a step or running the commands in the wrong directories to assure that all the steps are needed and in the specified order and in the proper directories.
=> docs: add missing step to test dapp docs

integration-tests/tx-rollup-l2-address.spec.ts
For the lima protocol, the instruction TICKET needs to be followed by ASSERT_SOME
fix #2170
=> test(integration-test): fixed tx-rollup-l2-address test for limanet

integration-tests/contract-originate-and-call-contract-lambda-rec.spec.ts, integration-tests/data/lambda-rec.ts
Deploy a contract written in plain michelson that contains the LAMBDA_REC instruction (test michel-codec and local-forging support of LAMBDA_REC inst). 
Call a contract having the type lambda in its entry point by passing a recursive lambda (test michelson-encoder package and local-forging package).
=> test(integration-test): lambda_rec

integration-tests/rpc-taquito.spec.ts
tried removing the unparsing mode and put it as something different but it fails.
the response of each is slightly different
and it fails when being sent with improper params at the http response level
=> add tests for parsing mode for all testnets, and fail case

.github/workflows/main.yml
This PR adds the ability to run integration tests against a Flextesa container running Lima protocol. Flextesa accepts additional parameters for provisioning bootstrap accounts. 
Moreover I refactored the workflow to use `matrix` strategy which reduces code duplication and improves the maintainability of the code. We will only need to append protocols in the `matrix` parameter whenever we want to support new protocols.
=> Add Flextesa Lima box and refactor the Github workflow

.github/workflows/deploy_edge.yml, .github/workflows/main.yml, integration-tests/config.ts, integration-tests/rpc-nodes.spec.ts
External PRs from users outside our `ecadlabs` GH org don't have access to GH Secrets. This is an intended behaviour to avoid exposing sensitive keys and tokens to third parties.
We block some resource-intensive RPC endpoints from our public-facing nodes. Since some integration tests need to contact these RPC endpoints we let GH runners join our private network and contact internal RPC Tezos nodes directly.  GH Runners use GH Secrets to join our Tailscale private network.
This PR refactors the GH workflows and skips the `baking_rights` and `endorsing_rights` tests when an external user submits a PR to Taquito. Additionally, we set the keygen `keyURL` to point to the publicly accessible keygen instance so that we can request keys without having to login to our private network. 
I've also …
=> Run integration test against testnets for external PRs

packages/taquito-local-forging/src/taquito-local-forging.ts
closes #2242 
Hotfix for bug where Lima protocol hash values aren't updated.
=> updated constant value for current protocol hash

docs/signing.md, packages/taquito-utils/test/format.spec.ts
update bytes length to have padding and divide hex string length to bytes length
closes #2185
=> fix bytes in signing data example

.github/workflows/algolia.yml, .github/workflows/bundle_webpack.yml, .github/workflows/deploy_edge.yml, .github/workflows/deploy_website.yml, .github/workflows/main.yml, .github/workflows/mondaynet.yml
Updated node version to 16.19.0 to fix `lerna version` command failing
=> Update all Github Workflows to use Node LTS Gallium (v16)

.github/workflows/main.yml, integration-tests/config.ts, integration-tests/contract-deploy-having-ticket.spec.ts, integration-tests/contract-increase-paid-storage-operation.spec.ts, integration-tests/contract-originate-and-call-contract-lambda-rec.spec.ts, integration-tests/contract-update-consensus-key-operation.spec.ts, integration-tests/injecting-multiple-manager-operations-in-a-block.spec.ts, integration-tests/known-contracts-PtLimaPtL.ts, integration-tests/known-contracts-PtMumbaii.ts, integration-tests/local-forging.spec.ts, integration-tests/package.json, integration-tests/rpc-get-protocol-constants.spec.ts, integration-tests/rpc-nodes.spec.ts, integration-tests/wallet-deploy-having-ticket.spec.ts, integration-tests/wallet-increase-paid-storage-operation.spec.ts, packages/taquito/src/constants.ts
closes #2290 
- Added new config values for Mumbai
- Added new protocol constants for Mumbai
- Added CI values in main.yml for Mumbai
=> update Taquito test configs to support Mumbai runs

integration-tests/data/instructions-with-bytes-contracts.ts, integration-tests/instructions-with-bytes.spec.ts, packages/taquito-michel-codec/src/michelson-typecheck.ts, packages/taquito-michel-codec/test/contracts_016.spec.ts, packages/taquito-michel-codec/test/contracts_016/opcodes/and_bytes.tz, packages/taquito-michel-codec/test/contracts_016/opcodes/lsl_bytes.tz, packages/taquito-michel-codec/test/contracts_016/opcodes/lsr_bytes.tz, packages/taquito-michel-codec/test/contracts_016/opcodes/not_bytes.tz, packages/taquito-michel-codec/test/contracts_016/opcodes/or_bytes.tz, packages/taquito-michel-codec/test/contracts_016/opcodes/xor_bytes.tz
add support for operations and, lsl/r, x/or and not to accept the type of bytes as a parameter 
closes #2267 
=> feat(michel-codec): add support for bytes 

integration-tests/data/instructions-bytes-conversions-contracts.ts, integration-tests/instructions-with-bytes-conversion.spec.ts, packages/taquito-local-forging/src/constants.ts, packages/taquito-michel-codec/src/binary.ts, packages/taquito-michel-codec/src/michelson-typecheck.ts, packages/taquito-michel-codec/src/michelson-types.ts, packages/taquito-michel-codec/src/michelson-validator.ts, packages/taquito-michel-codec/test/contracts_016.spec.ts, packages/taquito-michel-codec/test/contracts_016/opcodes/bytes_of_int.tz, packages/taquito-michel-codec/test/contracts_016/opcodes/bytes_of_nat.tz
adds support for bytes conversion bytes -> nat / int and vice versa
adds support to local-forger for the bytes code for BYTES and NAT instructions
close #2268
=> feat: start support bytes conversion 2268

integration-tests/contract-simple-transaction.spec.ts, packages/taquito-local-forging/src/codec.ts, packages/taquito-local-forging/test/codec.spec.ts
Open up validation to tz4 addresses so `transaction` operations can send **to** tz4 addresses
closes #2350 
=> 2350 tz4 validation

docs/smart_rollups.md, integration-tests/contract-batch-smart-rollup-add-messages.spec.ts, integration-tests/contract-batch.spec.ts, integration-tests/contract-smart-rollup-add-messages.spec.ts, packages/taquito/src/batch/rpc-batch-provider.ts, packages/taquito/src/contract/interface.ts, packages/taquito/src/contract/prepare.ts, packages/taquito/src/contract/rpc-contract-provider.ts, packages/taquito/src/estimate/estimate-provider-interface.ts, packages/taquito/src/estimate/rpc-estimate-provider.ts, packages/taquito/src/operations/operation-emitter.ts, packages/taquito/src/operations/smart-rollup-add-messages-operation.ts, packages/taquito/src/operations/types.ts, packages/taquito/src/prepare/prepare-provider.ts, packages/taquito/test/batch/rpc-batch-provider.spec.ts, packages/taquito/test/contract/helper.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts, packages/taquito/test/estimate/rpc-estimate-provider.spec.ts, packages/taquito/test/prepare/prepare-provider.spec.ts, website/sidebars.js, website/sidebars.json
Added smart_rollup_add_messages op support in the 
- estimate provider
- contract provider
- prepare provider
closes #2309 
=> Added support for smart_rollup_add_messages op and relevant tests

packages/taquito-utils/src/validators.ts, packages/taquito-utils/test/validators.spec.ts
closes #2398 
Fixed validation condition that allowed contract addresses to be more than the valid length
=> updated validation conditions for contractAddress

docs/signing.md
Full beacon signing example had invalid instructions for packing micheline data. It would sign but not unpack.
=> Correct example in signing docs

packages/taquito/src/prepare/prepare-provider.ts
Updated implementation of prepare provider to not carry over op counter amounts
closes #2425 
=> fixed prepare provider to not carry over counter amounts across methods

packages/taquito-rpc/src/opkind.ts, packages/taquito-rpc/src/types.ts, packages/taquito-rpc/test/data/rpc-responses.ts, packages/taquito-rpc/test/taquito-rpc.spec.ts
=> 2409 remaining smart rollup operation types

docs/events.md, integration-tests/polling-subscribe-provider.spec.ts, packages/taquito/src/subscribe/filters.ts, packages/taquito/src/subscribe/interface.ts, packages/taquito/src/subscribe/polling-subcribe-provider.ts, packages/taquito/test/subscribe/filters.spec.ts
closes #2319 
An optional field `excludeFailedOperations: boolean` is added to `EventFilter`. If this field is set to `true`, event will be propagated to the Dapp only when the result's `result.status` is `applied`.
An optional field `excludeFailedOperations: boolean` is added to `EventFilter`. If this field is set to `true`, event will be propagated to the Dapp only when the result's `result.status` is `applied`.
=> Implement the ability to filter out events from failed operations

docs/inmemory_signer.md
adds link to doc for InMemorySigner to closed github issue https://github.com/ecadlabs/taquito/issues/1764
for more visible reason why not to use in production or with sensitive/non-test data
=> docs: add link InMemorySigner doc

docs/tezos_domains.md
closes #2436 
clarify that `domain.address` is the address the domain name points to and `domain.owner` is the address that owns the domain name
=> docs: clarify doc for tezos domain names

integration-tests/tzip16-originate-contracts-with-metadata-on-HTTPS-and-sha256-hash-and-fetch-metadata.spec.ts
Yesterday I deleted one of our GCP Cloud storage buckets containing metadata for contracts used for taquito integration testing. I recovered all metadata files; however the sha256 hash for `taco-shop-metadata.json` differs due to the sorting order of the keys in the file causing the test in `tzip16-originate-contracts-with-metadata-on-HTTPS-and-sha256-hash-and-fetch-metadata.spec.ts` to fail.
In this PR I'm updating the sha256 hash for these test to match the one of the recovered `taco-shop-metadata.json` 
You can confirm that the metadata are the same by comparing previously deployed `taco-shop` contracts metadata with the `taco-shop-metadata.json` hosted in the GCP bucket:
- [https://mumbainet.tzkt.io/KT1Hz3DpqNciDLaJexLvktUaqRoKp9uQ9E89/metadata](https://mumbainet.tzkt.io/KT1Hz3DpqNciDL …
=> Update tzip16 contract metadata sha used in integration tests

integration-tests/contract-multisig-set-and-remove-delegate.spec.ts
will make the test more reliable by checking that there is not already an registered delegate.
CLOSES #2476
=> harden contract-multisig-set-and-remove-delegate.spec.ts against failing due to delegate already registered

docs/contract_call_parameters.md
closes #2443 
This approach to call an entrypoint can skip potential edge cases that have not been covered yet for the michelson-encoder
what the note section looks like
=> docs: add documentation for json michelson contract calls

packages/taquito/src/prepare/prepare-provider.ts
closes #2500 
Fixes contract call estimation behaviour to check for revealed keys
=> fixed contract call estimate prep to check for reveal

packages/taquito-signer/test/taquito-signer.spec.ts, packages/taquito-utils/src/taquito-utils.ts, packages/taquito-utils/test/taquito-utils.spec.ts
=> hex2buf now returns an error in case of an odd number of characters

packages/taquito-michelson-encoder/src/michelson-map.ts
Fixes #2251 by adding null to `MichelsonMapKey`.
I considered adding a test for (for example) `string | null`, but it seems the `MichelsonMap` tests are rather general and options are well-tested in tokens.
Please let me know if I should add a test that simply ensures the typescript type checks pass.
=> Add null to MichelsonMapKey

packages/taquito-michelson-encoder/src/tokens/pair.ts, packages/taquito-michelson-encoder/test/tokens/constant.spec.ts, packages/taquito-michelson-encoder/test/tokens/pair.spec.ts
=> fix: fixed idx calculation in pairs with mix of annotated and unanntated children

integration-tests/config.ts, integration-tests/known-contracts-ProtoALph.ts, integration-tests/known-contracts-PtGhostnet.ts, integration-tests/known-contracts-PtMumbai2.ts, integration-tests/known-contracts-PtNairobi.ts, integration-tests/known-contracts.ts, integration-tests/originate-known-contracts.ts, integration-tests/rpc-get-protocol-constants.spec.ts
Fixes #2163 
This is quite a hacky solution, where the values are only checked if they match an actual RPC endpoint. This means that RPC endpoints have to be updated in two places when they change.
Another possible solution: include a key in the test configurations `configuration.ts::Config` like `testnet: boolean` or `network_type: Testnet | Sandbox`. 
=> integration tests: don't hardcode testnet constant values

integration-tests/config.ts, integration-tests/known-contracts-ProtoALph.ts, integration-tests/known-contracts-PtGhostnet.ts, integration-tests/known-contracts-PtMumbai2.ts, integration-tests/known-contracts-PtNairobi.ts, integration-tests/known-contracts.ts, integration-tests/originate-known-contracts.ts, integration-tests/rpc-get-protocol-constants.spec.ts
@arvidj's contribution to update our integration test configs to not use hardcoded values 
=> integration tests: don't hardcode testnet constant values (#2164)

.github/workflows/main.yml
Ref #1690  
Reducing Jest maxWorkers to 4 decreases the chance to hit the ConnectionTimeout errors when running integration tests
=> Reduce jest maxWorkers to 4

.github/workflows/main.yml, integration-tests/config.ts, integration-tests/known-contracts-Proxford.ts, integration-tests/package.json, packages/taquito-local-forging/src/protocols.ts, packages/taquito-michel-codec/src/michelson-types.ts, packages/taquito/src/constants.ts
This PR adds Oxfordnet configuration to the integration tests
=> Add configuration for running integration tests against Oxfordnet

docs/rpc_package.md, packages/taquito-rpc/README.md
=> clarify in the docs that getBalance returns the balance in mutez

docs/quick_start.md, docs/wallet_API.md
=> Beacon events in docs

apps/taquito-test-dapp/src/App.svelte, apps/taquito-test-dapp/src/Layout.svelte, apps/taquito-test-dapp/src/config.ts, apps/taquito-test-dapp/src/lib/Sidebar.svelte, apps/taquito-test-dapp/src/lib/TestContainer.svelte, apps/taquito-test-dapp/src/lib/Wallet.svelte, apps/taquito-test-dapp/src/store.ts, apps/taquito-test-dapp/src/styles/index.scss, apps/taquito-test-dapp/vite.config.ts, cspell.json
Related to: #2707 
In the test dApp, all beacon events are now subscribed to and shown in the UI
=> Subscribe to all events in the test dApp

packages/taquito/src/contract/lambda-view.ts, packages/taquito/src/estimate/rpc-estimate-provider.ts, packages/taquito/src/operations/errors.ts, packages/taquito/src/provider.ts
It allows to find the faulty operation
Otherwise, it's just random guessing why it failed
=> Add more info to operation estimation errors in batches

packages/taquito/src/contract/lambda-view.ts, packages/taquito/src/estimate/rpc-estimate-provider.ts, packages/taquito/src/operations/errors.ts, packages/taquito/src/provider.ts
Follow up PR from @sergey-kintsel's contribution at https://github.com/ecadlabs/taquito/pull/2797 
It allows to find the faulty operation
Otherwise, it's just random guessing why it failed
=> Add more info to operation estimation errors in batches (#2797)

docs/sapling.md, docs/sapling_in_memory_viewing_key.md, website/package-lock.json, website/package.json, website/src/theme/CodeBlock/index.js, website/versioned_docs/version-17.2.0/sapling.md, website/versioned_docs/version-17.2.0/sapling_in_memory_viewing_key.md, website/versioned_docs/version-17.3.0/sapling.md, website/versioned_docs/version-17.3.0/sapling_in_memory_viewing_key.md, website/versioned_docs/version-17.4.0/sapling.md, website/versioned_docs/version-17.4.0/sapling_in_memory_viewing_key.md, website/versioned_docs/version-17.5.0/sapling.md, website/versioned_docs/version-17.5.0/sapling_in_memory_viewing_key.md, website/versioned_docs/version-19.0.0/sapling.md, website/versioned_docs/version-19.0.0/sapling_in_memory_viewing_key.md
Live code examples for Sapling were importing a file from its dependencies that has a 69MB file. This prevents the website from being deployed to Cloudflare due to the file size limit. It also potentially reduces performance of the website. 
This PR disables live code examples for Sapling. The static code examples will still be kept.
=> removed sapling deps and live code examples

docs/originate.md, docs/wallet_API.md, packages/taquito-beacon-wallet/README.md, website/versioned_docs/version-19.2.0/originate.md, website/versioned_docs/version-19.2.0/wallet_API.md
=> updated taquito/beacon-wallet readme to match beacon implementation

integration-tests/__tests__/contract/operations/staking.spec.ts, packages/taquito-core/src/errors.ts, packages/taquito/package.json, packages/taquito/src/contract/interface.ts, packages/taquito/src/contract/rpc-contract-provider.ts, packages/taquito/src/estimate/estimate-provider-interface.ts, packages/taquito/src/estimate/rpc-estimate-provider.ts, packages/taquito/src/operations/types.ts, packages/taquito/src/prepare/prepare-provider.ts, packages/taquito/test/contract/helper.ts, packages/taquito/test/contract/rpc-contract-provider.spec.ts, packages/taquito/test/estimate/rpc-estimate-provider.spec.ts, packages/taquito/test/prepare/prepare-provider.spec.ts
closes #2886 
- implemented stake, unstake, and finalize_unstake in the Contract API (estimate, prepare, contract provider)
- updated unit and integration tests
- updated types and interfaces to accommodate new pseudo operations
=> added staking support in contract API, with unit and integration tests

docs/rpc_nodes.md
closes [#2933](https://github.com/ecadlabs/taquito/issues/2933)
Adds the following Tezos Foundation links to the [RPC nodes page](https://taquito.io/docs/rpc_nodes/):
* Ghostnet: https://rpc.ghostnet.teztnets.com/
* Oxfordnet: https://rpc.oxfordnet.teztnets.com/
* Parisnet: https://rpc.parisnet.teztnets.com/
=> add Tezos Foundation RPCs

integration-tests/__tests__/contract/no-annotations-call-by-index-methodsObject.spec.ts, packages/taquito-michelson-encoder/src/taquito-michelson-encoder.ts, packages/taquito-michelson-encoder/src/tokens/or.ts, packages/taquito-michelson-encoder/src/tokens/pair.ts, packages/taquito-michelson-encoder/src/tokens/token.ts, packages/taquito-michelson-encoder/test/sample1.spec.ts, packages/taquito-michelson-encoder/test/sample11_dexter.spec.ts, packages/taquito-michelson-encoder/test/sample9_lambda.spec.ts, packages/taquito-michelson-encoder/test/tokens/or.spec.ts, packages/taquito/src/taquito.ts
This PR implements ability for developers to fall back to the legacy system for field numbering that is changed in #2929 
=> Using static variable to configure field numbering strategy

integration-tests/__tests__/contract/no-annotations-call-by-index-methodsObject.spec.ts, packages/taquito-michelson-encoder/src/taquito-michelson-encoder.ts, packages/taquito-michelson-encoder/src/tokens/createToken.ts, packages/taquito-michelson-encoder/src/tokens/or.ts, packages/taquito-michelson-encoder/src/tokens/pair.ts, packages/taquito-michelson-encoder/src/tokens/token.ts, packages/taquito-michelson-encoder/test/sample1.spec.ts, packages/taquito-michelson-encoder/test/sample11_dexter.spec.ts, packages/taquito-michelson-encoder/test/sample9_lambda.spec.ts, packages/taquito-michelson-encoder/test/tokens/map.spec.ts, packages/taquito-michelson-encoder/test/tokens/or.spec.ts, packages/taquito/src/taquito.ts, packages/taquito/test/contract/contractAbstraction.spec.ts
Closes #2927 
This is a breaking change in (In API behaviour, not the API itself).
Previously, when Michelson Data was converted to javascript objects (For instance, by calling `storage` method of a contract abstraction), in the following scenario we would have an unexpected behaviour:
1. The javascript representation has nested objects, like having a `pair`, inside an `or` inside another `pair`
2. Some of the `pair`'s items don't have `annots`.
In this case, the the resulting javascript object would look like this
```
{
'0': 'firstValue',
'1': 'secondValue,
'2': {
'2': 'thirdValue',
'3': 'fourthValue'
}
```
Please note the the inner object's field numbers depend on …
=> fix: the idx of a `pair` inside `or` inside `pair` is not calculated correctly

integration-tests/__tests__/contract/operations/staking.spec.ts
=> updated baker account for staking tests

packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
closes #2958 
Updated taquito beacon wallet to use `subscribeToEvent` instead of `getActiveAccount`
=> 2958 eventsub

packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
=> updated beacon wallet with new event sub

packages/taquito-local-forging/src/protocols.ts, packages/taquito-michel-codec/src/michelson-types.ts, packages/taquito/src/constants.ts
[internal] adding new protocol hash PtParisBxoLz5gzMmn3d9WBQNoPSZakgnkMC2VNuQ3KXfUtUQeZ after octez v20 release
=> feat: adding new protocol hash

.github/workflows/bundle_webpack.yml, .github/workflows/codeql-analysis.yml, .github/workflows/deploy_edge.yml, .github/workflows/deploy_test_dapp.yml, .github/workflows/main.yml, .github/workflows/mondaynet.yml
>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, cloudflare/pages-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
We need to upgrade some of our GitHub actions to newer versions to prevent any issues once the old versions are deprecated.
=> chore: update node v16 github actions

docs/cancel_http_requests.md, integration-tests/__tests__/contract/estimation-tests.spec.ts, packages/taquito-http-utils/src/taquito-http-utils.ts
closes #2973 
- updated taquito-http-util fetch call to include `keepalive=false`. Node 19 onwards now defaults keepalive to `true`, which were causing the socket hangup errors
=> added keepalive=false in createRequest

docs/michelson_encoder.md, website/src/theme/CodeBlock/index.js, website/versioned_docs/version-20.0.0/michelson_encoder.md
=> Add a section to Michelson Encoder doc about the breaking change, fix TypeCheck method example

integration-tests/__tests__/wallet/transfer-ticket-operation.spec.ts, packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts, packages/taquito/src/wallet/index.ts, packages/taquito/src/wallet/interface.ts, packages/taquito/src/wallet/legacy.ts, packages/taquito/src/wallet/operation-factory.ts, packages/taquito/src/wallet/transfer-ticket-operation.ts, packages/taquito/src/wallet/wallet.ts
=> added transfer ticket to the wallet API and updated integration tests

packages/taquito-beacon-wallet/test/__mocks__/broadcast-channel.ts, packages/taquito-beacon-wallet/test/taquito-beacon-wallet.spec.ts
Hi all,
After extensive investigation, it appears that the issue lies not with the `broadcast-channel` module itself, but with the base `BroadcastChannel` module, as using the latter also results in the same problems.
Additionally, for some reason, Jest is detecting a timeout inside [PostMessageTransport](https://github.com/airgap-it/beacon-sdk/blob/master/packages/beacon-transport-postmessage/src/PostMessageTransport.ts#L87-#L92) as an open handle.
To address this, I have mocked the entire class and used fake timers to ensure handles are freed promptly.
Thank you in advance for the time you will dedicate to reviewing my PR.
=> fix: beacon-wallet open handles in tests

packages/taquito/src/operations/index.ts
Adding `SmartRollupExecuteOutboxMessageParams` to the list of exported types. 
It is used in `ParamsWithKind` but it's only one which was not exported.
=> fix: adding export for SmartRollupExecuteOutboxMessageParams

package-lock.json, website/package-lock.json
=> Update deps 20240917

apps/taquito-test-dapp/src/lib/TestContainer.svelte, apps/taquito-test-dapp/src/lib/Wallet.svelte, apps/taquito-test-dapp/src/tests.ts, docs/wallet_connect_2.md, package.json, packages/taquito-wallet-connect-2/README.md, packages/taquito-wallet-connect-2/src/errors.ts, packages/taquito-wallet-connect-2/src/taquito-wallet-connect-2.ts, packages/taquito-wallet-connect-2/src/types.ts, packages/taquito-wallet-connect-2/test/taquito-wallet-connect-2.spec.ts
Added support to sign payload in the test-dapp using wallet connect, fix getPk and sign in the wallet connect package
=> feat(wallet connect): sign payload using wc in test-dapp

packages/taquito-http-utils/package.json, packages/taquito-http-utils/rollup.config.ts, packages/taquito-http-utils/src/taquito-http-utils.ts
Fixes the issue mentioned in #2973.
It was supposedly resolved by #2986, but in Node.js v20 and later, `fetch` requires an explicit HTTP/HTTPS agent with `keepAlive: false`—setting `keepalive: false` alone is not sufficient/effective.
=> Keepalive false for node v19+
