- packages/tezos-ts-react-components/.storybook/addons.ts
- packages/tezos-ts-react-components/.storybook/config.ts
- packages/tezos-ts-react-components/.storybook/theme.ts
- packages/tezos-ts-react-components/package-lock.json
- packages/tezos-ts-react-components/package.json
- packages/tezos-ts-react-components/src/balance.tsx
- packages/tezos-ts-react-components/src/format.ts
- packages/tezos-ts-react-components/stories/index.stories.tsx
Add formatting options to balance component
> feat(react-components): Add formatting options to balance component

- packages/tezos-ts-rpc/src/tezos-ts-rpc.ts
- packages/tezos-ts-rpc/src/types.ts
- packages/tezos-ts-rpc/test/tezos-ts-rpc.spec.ts
> feat(rpc): Add getDelegates (baker) endpoint support to RPC

- example/example-node.ts
- packages/tezos-ts-rpc/src/tezos-ts-rpc.ts
- packages/tezos-ts-rpc/src/types.ts
- packages/tezos-ts-rpc/src/utils/utils.ts
- packages/tezos-ts-rpc/test/tezos-ts-rpc.spec.ts
Not ready for merging yet. 
Created PR for reviewing and discussion.
> #9 Get block 

- packages/tezos-ts-http-utils/src/tezos-ts-http-utils.ts
- packages/tezos-ts-react-components/package-lock.json
- packages/tezos-ts-react-components/package.json
- packages/tezos-ts-react-components/src/balance-history.tsx
- packages/tezos-ts-react-components/stories/balance-history.stories.tsx
- packages/tezos-ts-rpc/src/tezos-ts-rpc.ts
- packages/tezos-ts-rpc/test/tezos-ts-rpc.spec.ts
- packages/tezos-ts/src/subscribe/interface.ts
- packages/tezos-ts/src/subscribe/polling-provider.ts
- packages/tezos-ts/src/tezos-ts.ts
Add balance history component to react component library
re #14
> Balance history component

- packages/tezos-ts-react-components/src/format.ts
- packages/tezos-ts/src/format.ts
- packages/tezos-ts/src/tezos-ts.ts
- packages/tezos-ts/test/format.spec.ts
> feat(tezos-ts): Add format utilities to tezos-ts class

- packages/tezos-ts/package-lock.json
- packages/tezos-ts/package.json
- packages/tezos-ts/src/context.ts
- packages/tezos-ts/src/contract/interface.ts
- packages/tezos-ts/src/contract/operations.ts
- packages/tezos-ts/src/contract/rpc-contract-provider.ts
- packages/tezos-ts/src/signer/interface.ts
- packages/tezos-ts/src/signer/noop.ts
- packages/tezos-ts/src/subscribe/polling-provider.ts
- packages/tezos-ts/src/tezos-ts.ts
- packages/tezos-ts/src/tz/rpc-tz-provider.ts
- packages/tezos-ts/test/contract/data.ts
- packages/tezos-ts/test/contract/rpc-contract-provider.spec.ts
- packages/tezos-ts/test/tezos-ts.spec.ts
- packages/tezos-ts/test/tz/rpc-tz-provider.spec.ts
Also refactor the way we propagate rpc and signer through the library
> feat(tezos-ts): Provide high level function to inject operation into node

- packages/tezos-ts-rpc/src/tezos-ts-rpc.ts
- packages/tezos-ts-rpc/src/types.ts
- packages/tezos-ts-rpc/test/tezos-ts-rpc.spec.ts
> #33 Voting utility

- packages/tezos-ts-http-utils/src/tezos-ts-http-utils.ts
- packages/tezos-ts-rpc/src/tezos-ts-rpc.ts
- packages/tezos-ts-rpc/src/types.ts
- packages/tezos-ts-rpc/src/utils/utils.ts
- packages/tezos-ts-rpc/test/tezos-ts-rpc.spec.ts
> #34 getBakingRights

- packages/tezos-ts-rpc/src/tezos-ts-rpc.ts
- packages/tezos-ts-rpc/src/types.ts
- packages/tezos-ts-rpc/test/tezos-ts-rpc.spec.ts
> #65 getEndorsingRights

- docs/quick_start.md
- example/contract-origination.ts
- packages/tezos-ts-signer/src/ed-key.ts
- packages/tezos-ts-signer/src/tezos-ts-signer.ts
- packages/tezos-ts-signer/test/tezos-ts-signer.spec.ts
- packages/tezos-ts/package.json
- packages/tezos-ts/src/tezos-ts.ts
- packages/tezos-ts/test/tezos-ts.spec.ts
Add some tests for invalid address
> feat(tezos-ts): Add import key high level function

- example/contract-origination.ts
- packages/tezos-ts/src/tezos-ts.ts
- packages/tezos-ts/test/tezos-ts.spec.ts
- packages/tezos-ts/test/tz/rpc-tz-provider.spec.ts
> feat(tezos-ts): Support faucet account in import key

- example/contract-origination.ts
- packages/tezos-ts/src/contract/interface.ts
- packages/tezos-ts/src/contract/rpc-contract-provider.ts
- packages/tezos-ts/src/operations/operation-emitter.ts
- packages/tezos-ts/src/operations/origination-operation.ts
- packages/tezos-ts/src/operations/types.ts
- packages/tezos-ts/src/tz/rpc-tz-provider.ts
- packages/tezos-ts/test/operations/origination-operation.spec.ts
> feat(tezos-ts): Add access to originated address in Origination Operation

- README.md
It's unclear for me if it will render properly everywhere, TypeDoc, Github etc
> docs(readme) Add logo to main readme

- CONTRIBUTING.md
- README.md
- code-of-conduct.md
- docs/inmemory_signer.md
- docs/quick_start.md
Add CII badge
Copy edits, minor typo fixes
> docs: Copy edits and new CII badge

- packages/taquito-michelson-encoder/data/multisig.ts
- packages/taquito-michelson-encoder/src/schema/parameter.ts
- packages/taquito-michelson-encoder/src/tokens/option.ts
- packages/taquito-michelson-encoder/src/tokens/or.ts
- packages/taquito-michelson-encoder/src/tokens/pair.ts
- packages/taquito-michelson-encoder/src/tokens/token.ts
- packages/taquito-michelson-encoder/test/baker_registry.spec.ts
- packages/taquito-michelson-encoder/test/manager.spec.ts
- packages/taquito-michelson-encoder/test/proto005/multisig.spec.ts
- packages/taquito-michelson-encoder/test/proto005/unit_contract.spec.ts
- packages/taquito-michelson-encoder/test/sample1.spec.ts
- packages/taquito-michelson-encoder/test/sample10.spec.ts
- packages/taquito-michelson-encoder/test/sample11_dexter.spec.ts
- packages/taquito-michelson-encoder/test/sample12_vote_delegation.spec.ts
- packages/taquito-michelson-encoder/test/sample3.spec.ts
- packages/taquito-michelson-encoder/test/sample6.spec.ts
- packages/taquito-michelson-encoder/test/sample8.spec.ts
- packages/taquito-michelson-encoder/test/sample9_lambda.spec.ts
- packages/taquito/src/contract/contract.ts
- packages/taquito/src/contract/errors.ts
- packages/taquito/src/contract/utils.ts
Now provide concrete signature error with SC abstraction and fix a bug for encoding or token
parameter
> feat(michelson-encoder): Add support for signature extraction from schema

- integration-tests/contract-api-scenario.spec.ts
- integration-tests/data/boolean_parameter.ts
- packages/taquito-michelson-encoder/data/sample14_bool_parameter.ts
- packages/taquito-michelson-encoder/src/tokens/comparable/bool.ts
- packages/taquito-michelson-encoder/test/sample14_bool_parameter.spec.ts
> fix(michelson-encoder): Fix improper encoding of boolean parameters

- packages/taquito/src/constants.ts
- packages/taquito/test/contract/rpc-contract-provider.spec.ts
> fix(taquito): Change default storage limit constant for reveal and transaction

- docs/making_transfers.md
- docs/quick_start.md
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
- website/src/css/custom.css
- website/src/theme/CodeBlock/index.js
- website/src/theme/CodeBlock/styles.module.css
- website/src/theme/Playground/index.js
- website/src/theme/Playground/styles.module.css
- website/yarn.lock
* Swizzled CodeBlock and Playground components to make examples runnable
* Added runnable examples
> Runnable examples

- integration-tests/config.ts
- integration-tests/contract-api-scenario.spec.ts
- integration-tests/data/bigmap_with_pair_as_key.ts
- packages/taquito-michelson-encoder/src/tokens/pair.ts
- packages/taquito-michelson-encoder/src/tokens/token.ts
- packages/taquito-michelson-encoder/test/tokens/pair.spec.ts
Support pair as big map key
**Note**: pair are still not supported for map and set
re #251
> feat(michelson-encoder): Allow using pair to fetch big map value

- packages/taquito-local-forging/src/codec.ts
- packages/taquito-local-forging/test/zarith.spec.ts
> fix(local-forging): Fix zarith encoding error

- integration-tests/contract-api-scenario.spec.ts
- packages/taquito-local-forging/test/taquito-local-forging.spec.ts
> test(local-forging): Add test case for non ascii char against RPC node

- packages/taquito-rpc/src/taquito-rpc.ts
- packages/taquito/src/contract/interface.ts
- packages/taquito/src/contract/rpc-contract-provider.ts
> fix(docs): Fix TypeDoc @see URLs to point to Tezos RPC documentation

- integration-tests/multisig-contract-scenario.spec.ts
Make the multisig integration tests use 2 out of 3 signatures policy instead of a 1 out of 1.
> test(integration): Improve multisig tests to use 2 out of 3 signatures

- integration-tests/contract-api-scenario.spec.ts
- packages/taquito/src/contract/contract.ts
> feat(taquito): Allow mutez and source option  in smart contract calls

- integration-tests/taquito-rpc.spec.ts
- packages/taquito-rpc/src/taquito-rpc.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
> feat(taquito-rpc.spec integration-tests): add tests/documentation for different getBlock syntaxes

- example/contract-origination.ts
- example/contract-origination2.ts
- example/contract-origination3.ts
- integration-tests/config.ts
- packages/taquito-remote-signer/src/taquito-remote-signer.ts
- packages/taquito-signer/package-lock.json
- packages/taquito-signer/package.json
- packages/taquito-signer/src/import-key.ts
- packages/taquito-signer/src/taquito-signer.ts
- packages/taquito-signer/test/import-key.spec.ts
- packages/taquito/package-lock.json
- packages/taquito/package.json
- packages/taquito/src/taquito.ts
- packages/taquito/test/taquito.spec.ts
- website/package-lock.json
Implements: #144 
Paritally fixes: #314
> 212 remove signer from taquito core

- docs/quick_start.md
- docs/smartcontracts.md
- website/src/theme/CodeBlock/index.js
- website/src/theme/Playground/index.js
- website/yarn.lock
* Added a new function for printing output without losing previous messages
> Keeping output history with println

- docs/quick_start.md
- docs/smartcontracts.md
- website/src/theme/Playground/index.js
* Setting signing key behind the scenes
> Auto-importing key

- website/src/css/custom.css
> style(docs website): fix overflow issue for small screens

- packages/taquito-signer/src/ec-key.ts
- packages/taquito-signer/test/taquito-signer.spec.ts
Implemented a padding solution to ensure that signatures length is 64 bytes as suggested in this
issue https://github.com/indutny/elliptic/issues/195
> fix(signer): Some signatures were invalid (s value too short) for ec key

- integration-tests/contract-origination-wrong-order-code-porps.spec.ts
- integration-tests/data/smartpy-example-contract.ts
- packages/taquito/src/contract/prepare.ts
- packages/taquito/src/contract/rpc-contract-provider.ts
- packages/taquito/src/operations/operation-emitter.ts
- packages/taquito/test/contract/data.ts
- packages/taquito/test/contract/rpc-contract-provider.spec.ts
Some HLL's (SmartPy) produce JSON represented Michelson in an order that is not accepted by the
Tezos Node RPC.
> fix(origination): Ensure correct order of code properties

- example/package-lock.json
- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
- packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
- packages/taquito-tezbridge-wallet/package-lock.json
- website/package-lock.json
#354
This PR updates the beacon-sdk dependency for taquito-beacon-wallet to 0.3.0-beta.1. Updates  the types and adapts the wallet to the latest changes.
> feat(taquito-beacon-wallet): Update the beacon-sdk to 0.3.0-beta.2

- docs/inmemory_signer.md
Relates to issue pointed out in #364, thank you @Bladrak
Fixes to the InMemorySigner website documentation
> doc(website) Use static method when using InMem signer

- docs/estimate.md
- packages/taquito/src/contract/estimate.ts
- website/sidebars.json
- website/src/theme/Playground/index.js
- Added a new page to the taquito website documentation with examples to estimate transfer operation, smart contract call and smart contract origination
- Improved description in TypeDoc and added 2 examples of use
> Estimate Documentation

- integration-tests/package-lock.json
- integration-tests/package.json
- package.json
- packages/taquito-http-utils/package-lock.json
- packages/taquito-http-utils/package.json
- packages/taquito-local-forging/package-lock.json
- packages/taquito-local-forging/package.json
- packages/taquito-michel-codec/package-lock.json
- packages/taquito-michel-codec/package.json
- packages/taquito-michelson-encoder/package-lock.json
- packages/taquito-michelson-encoder/package.json
- packages/taquito-react-components/package-lock.json
- packages/taquito-react-components/package.json
- packages/taquito-remote-signer/package-lock.json
- packages/taquito-remote-signer/package.json
- packages/taquito-rpc/package-lock.json
- packages/taquito-rpc/package.json
- packages/taquito-signer/package-lock.json
- packages/taquito-signer/package.json
- packages/taquito-tezbridge-signer/package-lock.json
- packages/taquito-tezbridge-signer/package.json
- packages/taquito-utils/package-lock.json
- packages/taquito-utils/package.json
- packages/taquito/package-lock.json
- packages/taquito/package.json
Updated all Typescript dependencies to 3.9.5
> chore(deps): Update to typescript 3.9.5

- docs/validators.md
- packages/taquito-utils/src/taquito-utils.ts
- packages/taquito-utils/src/validators.ts
- website/sidebars.json
- website/src/theme/CodeBlock/index.js
Added a demo page for the validation functions to Taquito website and added examples/descriptions to TypeDoc
> Documentation for validation functions of Taquito-utils

- docs/quick_start.md
> Corrected a typo in the docs

- packages/taquito-michel-codec/src/micheline-emitter.ts
- packages/taquito-michel-codec/src/micheline-parser.ts
- packages/taquito-michel-codec/src/michelson-validator.ts
- packages/taquito-michel-codec/src/utils.ts
- packages/taquito/test/contract/data.ts
- packages/taquito/test/contract/rpc-contract-provider.spec.ts
> run time type checking for confident JavaScript developers

- docs/maps_bigmaps.md
Edited the documentation to replace JSON Michelson by Michelson in examples.
> Modified map / BigMap doc to replace JSON Michelson by Michelson

- website/package-lock.json
- website/package.json
Updated "@taquito/taquito": "^6.3.0-wallet.3" to "@taquito/taquito": "^6.3.3-beta.0" on website
> updated Taquito version on website/package.json

- docs/storage_annotations.md
- website/sidebars.json
- website/src/theme/Playground/index.js
Added documentation to show how to write storage when it is annotated or not.
> Examples of storage with and without annotations

- docs/originate.md
- website/package-lock.json
- website/package.json
- website/src/theme/CodeBlock/index.js
- website/src/theme/Playground/index.js
Added an explanation that "plains" Michelson can now be used for contract origination.
Added examples of origination with the wallet API.
> Reviewed the originating contracts documentation

- docs/inmemory_signer.md
- website/src/css/custom.css
- website/src/theme/CodeBlock/index.js
Added examples of secret keys and an example of using the b58cencode function.
> Update documentation clarifying secret key format

- packages/taquito-michel-codec/src/macros.ts
- packages/taquito-michel-codec/test/macros.spec.ts
> Expand DIIP/DUUP macros

- .github/workflows/main.yml
We have set-up Github Actions for Taquito's CI processes. We will sunset circleci in due course.
> GitHub actions jev

- packages/taquito-michel-codec/src/macros.ts
- packages/taquito-michel-codec/test/macros.spec.ts
> UNPAIR macro expansion fixed

- docs/ledger_integration_test.md
- docs/ledger_signer.md
- example/scan-path-ledger.ts
- integration-tests/ledger-signer-falling-tests.spec.ts
- integration-tests/ledger-signer.spec.ts
- integration-tests/package.json
- packages/taquito-ledger-signer/src/taquito-ledger-signer.ts
- packages/taquito-ledger-signer/src/utils.ts
- packages/taquito-ledger-signer/test/taquito-ledger-signer.spec.ts
- Fixed the tab code example in the doc.
- Added falling tests and documentation for these tests on the website.
> Ledger signer

- .github/workflows/deploy_website.yml
Removed the react-storybook from the jobs of the website since it is not use any more.
> Remove storybook from the website jobs

- docs/rpc_nodes.md
- docs/rpc_nodes_integration_test.md
- integration-tests/rpc-nodes.spec.ts
- website/sidebars.json
- Added Delphinet to the new RPC nodes integration tests which show which endpoints work on which nodes. (I started only with Carthagenet)
- Added a documentation page on how to run these tests.
> Improved RPC nodes integration test

- docs/ledger_signer.md
- example/scan-path-ledger.ts
- integration-tests/ledger-signer-falling-tests.spec.ts
- integration-tests/ledger-signer.spec.ts
- packages/taquito-ledger-signer/src/taquito-ledger-signer.ts
- packages/taquito-ledger-signer/test/taquito-ledger-signer.spec.ts
> Changes to the Ledger signer

- docs/quick_start.md
- docs/v7_breaking_changes.md
- website/sidebars.json
> docs(v7_upgrade): copy-editing and formatting

- docs/batch-api.md
- docs/quick_start.md
- website/package-lock.json
- website/sidebars.json
This pull request includes the corrected documentation as per issue #488 and the new documentation for the batch API.
> Updated documentation

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> Updated beacon-sdk to 1.2.0

- packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
Removed methods that are accessible from the DAppClient instance.
> Removed some methods from BeaconWallet

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> Updated beacon-sdk 2.0.0-beta.16

- docs/tutorial_links.md
- website/sidebars.json
Added new page with tutorial links
> Added new page with tutorial links

- example/deploy-lambda-contract.ts
The path was wrong for the import of VIEW_LAMBDA. Fixed it.
> Fixed import path for VIEW_LAMBDA in the example

- docs/michelsonmap.md
- website/sidebars.json
Added documentation for MichelsonMap class
> Added corrected documentation for MichelsonMap class

- docs/lambda_view.md
- packages/taquito/src/contract/index.ts
#536 
The export was missing in the index.ts file
Also corrected the path on the website documentation
> Fix VIEW_LAMBDA export

- docs/wallet_API.md
Edited the Wallet API documentation to emphasize the use of Beacon over the separate libraries for Thanos and TezBridge.
> Edited Wallet API documentation

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
Updated to the latest Beacon v2.2.0 release https://github.com/airgap-it/beacon-sdk/releases/tag/v2.2.0
> chore: update to latest beacon-sdk release v2.2.0

- packages/taquito-michel-codec/src/michelson-typecheck.ts
> Don't pass parent contract to lambdas

- integration-tests/config.ts
- integration-tests/contract-estimation-tests.spec.ts
- integration-tests/contract-originate-contract-unpair.spec.ts
- integration-tests/contract-originate-contract-with-sapling.spec.ts
- integration-tests/contract-originate-invalid-string.spec.ts
- integration-tests/edo-deploy-contract-having-ticket.spec.ts
- integration-tests/ledger-signer.spec.ts
- integration-tests/wallet-originate-contract-unpair.spec.ts
- packages/taquito-michel-codec/src/macros.ts
- packages/taquito-michel-codec/src/michelson-typecheck.ts
- packages/taquito-michel-codec/src/michelson-types.ts
- packages/taquito-michel-codec/test/contracts_008.spec.ts
- packages/taquito-michel-codec/test/macros.spec.ts
- packages/taquito-tzip16/src/viewKind/michelson-storage-view.ts
- packages/taquito/src/constants.ts
- packages/taquito/test/parser/michel-codec-parser.spec.ts
> Replace edo version

- integration-tests/config.ts
- integration-tests/contract-estimation-tests.spec.ts
- integration-tests/contract-originate-contract-unpair.spec.ts
- integration-tests/contract-originate-contract-with-sapling.spec.ts
- integration-tests/contract-originate-invalid-string.spec.ts
- integration-tests/edo-deploy-contract-having-ticket.spec.ts
- integration-tests/wallet-originate-contract-unpair.spec.ts
- packages/taquito-michel-codec/src/macros.ts
- packages/taquito-michel-codec/src/michelson-typecheck.ts
- packages/taquito-michel-codec/src/michelson-types.ts
- packages/taquito-michel-codec/test/contracts_008.spec.ts
- packages/taquito-michel-codec/test/macros.spec.ts
- packages/taquito-tzip16/src/viewKind/michelson-storage-view.ts
- packages/taquito/src/constants.ts
- packages/taquito/test/parser/michel-codec-parser.spec.ts
> Fixed typo

- integration-tests/config.ts
- integration-tests/contract-originate-contract-with-sapling.spec.ts
- packages/taquito-local-forging/src/michelson/codec.ts
- packages/taquito-local-forging/test/data/code_with_sapling.ts
- packages/taquito-local-forging/test/data/code_with_ticket.ts
- packages/taquito-local-forging/test/taquito-local-forging.spec.ts
- packages/taquito-michelson-encoder/data/sample19_sapling.ts
> Support for comb pairs in the local-forging

- docs/lambda_view.md
- packages/taquito/src/contract/lambda-view.ts
> LambdaView: Return an appropriate error when no signer is configured 

- integration-tests/config.ts
- integration-tests/contract-estimation-tests.spec.ts
- integration-tests/tzip16-originate-contract-having-metadata-on-IPFS-and-fetch-those.spec.ts
- Fixed the estimation test (2 mutez difference).
- Replaced the public gateway for IPFS from 'gateway.ipfs.io' to 'cloudflare-ipfs.com', to see if the requests will timeout less often.
- log error from the keygen in the console: #629
> fix integration tests

- .github/workflows/deploy_website.yml
- .github/workflows/preview_website.yml
- typedoc.js
The tezos taquito website is not hosted on Netlify, and we produce preview builds on all PR's making it easier to make and review contributions :tada:
> Fix typedoc gen for netlify

- docs/batch-api.md
- integration-tests/contract-estimation-tests.spec.ts
- integration-tests/manager-wallet-scenario.spec.ts
- integration-tests/multisig-contract-scenario.spec.ts
- integration-tests/multisig-wallet-scenario.spec.ts
- integration-tests/wallet-ligo-increment-contract.spec.ts
- integration-tests/wallet-manager-that-calls-failwith-contract.spec.ts
- integration-tests/wallet-michelson-origination.spec.ts
- integration-tests/wallet-no-annotations-call-by-index.spec.ts
- integration-tests/wallet-originate-contract-with-bool.spec.ts
- integration-tests/wallet-originate-contract-with-sapling.spec.ts
- integration-tests/wallet-originate-invalid-string.spec.ts
- integration-tests/wallet-originate-token-contract.spec.ts
- integration-tests/wallet-originate-vote-contract.spec.ts
- integration-tests/wallet-origination-wrong-order-code-properties.spec.ts
- integration-tests/wallet-pair-as-key.spec.ts
- integration-tests/wallet-set-delegate-auto-estimate.spec.ts
- integration-tests/wallet-simple-origination.spec.ts
- integration-tests/wallet-tx-wait-2-confirmations.spec.ts
- integration-tests/wallet-unit-as-param.spec.ts
- integration-tests/wallet-with-bad-code.spec.ts
- integration-tests/wallet-with-bigmap-init.spec.ts
These are the remaining contract integration tests wallet API versions,.
> Deploy the rest of the  wallet contract integration tests

- integration-tests/wallet-originate-vote-contract.spec.ts
> Skip wallet-originate-vote-contract.spec.ts for falphanet

- docs/lambda_view.md
- docs/maps_bigmaps.md
> Removed the pre release warning about lambda views form Taquito Docs

- integration-tests/contract-register-delegate.spec.ts
- integration-tests/wallet-register-delegate.spec.ts
- packages/taquito/src/contract/interface.ts
> Added coverage test for register delegate

- .github/workflows/deploy_edge.yml
- .github/workflows/main.yml
> run locally installed lerna properly, improve triggeres on test and deploy edge

- .github/workflows/main.yml
> chore: Added environment variables to the main.yml workflow jobs

- docs/version.md
- docs/wallet_API.md
Changed Thanos to Temple in descriptive docs, not code
CLOSE #688
> Changed Thanos to Temple in descriptive docs, not code

- .github/workflows/deploy_edge.yml
> announce preview packages in PR comment

- .github/workflows/deploy_edge.yml
> Fix preview package names in automatic PR comment

- package-lock.json
- package.json
- packages/taquito-local-forging/package-lock.json
- packages/taquito-local-forging/package.json
- packages/taquito-michel-codec/package-lock.json
- packages/taquito-michel-codec/package.json
- packages/taquito-michelson-encoder/package-lock.json
- packages/taquito-michelson-encoder/package.json
- packages/taquito-remote-signer/package-lock.json
- packages/taquito-remote-signer/package.json
- packages/taquito-signer/package-lock.json
- packages/taquito-signer/package.json
- packages/taquito-tzip12/package-lock.json
- packages/taquito-tzip12/package.json
- packages/taquito-tzip16/package-lock.json
- packages/taquito-tzip16/package.json
- packages/taquito-utils/package-lock.json
- packages/taquito-utils/package.json
Updated typedoc, jest, and elliptic. This should address Dependabot alerts.
> Dependencies update

- packages/taquito-rpc/test/taquito-rpc.spec.ts
> added unit test for getBlock transaction

- packages/taquito-rpc/src/taquito-rpc.ts
- packages/taquito/src/contract/contract.ts
- packages/taquito/src/contract/interface.ts
- packages/taquito/src/contract/rpc-contract-provider.ts
Updates to typedoc RPC reference links.
> chore: correct @see url's in RPC typedoc comments

- example/example-parallel-bigmap-local-vs-rpc-pack.ts
- example/example-sequential-bigmap-local-vs-rpc-pack.ts
- example/package-lock.json
- example/package.json
In the examples, we fetch the big map values using the RPC to pack, then we fetch the values by packing locally and we compare the time it took to do both.
The contract used in the examples has 810 entries on the big map.
There are 3 constants at the top of the file that can be changed if needed:
```
const rpc = 'https://api.tez.ie/rpc/edonet';
const numberOfValueToFetch = 810; // max 810
const repeat = 2; // How many time we want to fetch all the keys
```
To run the example where the requests are done in sequence:
```
cd example
example:rpc-vs-local-pack-sequential
```
To run the example where the requests are done in parallel:
```
cd example
example:rpc-vs-local-pack-parallel
```
__If relevant, …
> Examples fetch many big map values in sequence and parallel

- packages/taquito-michel-codec/src/michelson-typecheck.ts
- packages/taquito-rpc/src/taquito-rpc.ts
- packages/taquito-rpc/src/types.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
> Issue-601 New RPC endpoints

- integration-tests/contract-estimation-tests.spec.ts
> update estimates in integration tests

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> Update beacon-sdk to v2.2.3

- packages/taquito-michelson-encoder/src/tokens/lambda.ts
- packages/taquito-michelson-encoder/test/tokens/lambda.spec.ts
> Fix LambdaToken.Execute

- integration-tests/ledger-signer.spec.ts
> minor changes for ledger wallet integration tests

- docs/batch-api.md
- docs/estimate.md
- docs/michelsonmap.md
- docs/wallet_API.md
> Corrected broken links in Taquito online docs

- website/docusaurus.config.js
Close #746 - added telegram to community links
> added link to Telegram to community links in Taquito Docs footer

- integration-tests/rpc-nodes.spec.ts
- packages/taquito-rpc/src/taquito-rpc.ts
> Fixed URL in RPC reference for #post-block-id-helpers-scripts-run-code and update rpc tests to edo and florence

- packages/taquito-michel-codec/src/utils.ts
> Critical list like combs handling bug fix

- packages/taquito/src/context.ts
- packages/taquito/src/subscribe/observable-subscription.ts
- packages/taquito/src/subscribe/polling-provider.ts
- packages/taquito/test/subscribe/observable-subscription.spec.ts
> Item-724 Subscription retries limited to 10 with 1 second time interval

- integration-tests/contract-originate-invalid-string.spec.ts
> added retry contract-originate-invalid-string integration-test

- integration-tests/contract-originate-contract-unpair.spec.ts
- integration-tests/encode-long-numeral.spec.ts
- integration-tests/wallet-empty-unrevealed-implicit-account.spec.ts
- integration-tests/wallet-failwith.spec.ts
> added jest retry for contract-originate-contract-unpair.spec.ts

- integration-tests/manager-contract-scenario.spec.ts
- integration-tests/manager-wallet-scenario.spec.ts
- integration-tests/multisig-contract-scenario.spec.ts
- integration-tests/multisig-wallet-scenario.spec.ts
Close #797 - removed Babylon 005 from test names
> removed babylon/005 references in test names

- docs/version.md
- website/docusaurus.config.js
Close #801  
need to update the version in Taquito online docs to 8.1.1
> updated version for taquito docs

- docs/rpc_nodes_integration_test.md
> update rpc docs page

- docs/michelsonmap.md
- docs/signing.md
- docs/wallet_API.md
- website/package-lock.json
- website/sidebars.json
- website/yarn.lock
This pull request contains 3 changes in the documentation:
- I added the new article about signing data with Taquito
-  I updated the Wallet API documentation to demonstrate how to use Kukai on testnet
- I updated the MichelsonMap documentation and originated the example contract to Edonet as per https://github.com/ecadlabs/taquito/issues/463
> Documentation update

- .gitignore
- packages/taquito-beacon-wallet/package.json
- packages/taquito-http-utils/package.json
- packages/taquito-ledger-signer/package.json
- packages/taquito-local-forging/package.json
- packages/taquito-michel-codec/package.json
- packages/taquito-michelson-encoder/package.json
- packages/taquito-remote-signer/package.json
- packages/taquito-rpc/package.json
- packages/taquito-signer/package.json
- packages/taquito-tezbridge-signer/package.json
- packages/taquito-tezbridge-wallet/package.json
- packages/taquito-tzip12/package.json
- packages/taquito-tzip16/package.json
- packages/taquito-utils/package.json
- packages/taquito/package.json
- packages/taquito/src/taquito.ts
- packages/taquito/test/taquito.spec.ts
- packages/taquito/version-stamping.js
> Issue-638 Expose version and git hash for all packages

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
Updated beacon sdk version to v2.2.4
> Updated beacon sdk version to v2.2.4

- website/docusaurus.config.js
update the Taquito online docs to show version 9.0.0
There is no issue to close, just this PR
> changed version in docs to 9.0.0

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> Updated beacon-sdk to v2.2.5

- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy_website.yml
- .github/workflows/main.yml
- .github/workflows/preview_website.yml
> chore: Configure all workflows to run on private runners

- docs/complex_parameters.md
- docs/drain_account.md
- docs/estimate.md
- docs/inmemory_signer.md
- docs/lambda_view.md
- docs/ledger_signer.md
- docs/making_transfers.md
- docs/maps_bigmaps.md
- docs/metadata-tzip16.md
- docs/michelsonmap.md
- docs/originate.md
- docs/quick_start.md
- docs/rpc_package.md
- docs/set_delegate.md
- docs/smartcontracts.md
- docs/storage_annotations.md
- docs/tzip12.md
- docs/validators.md
- docs/wallet_API.md
- integration-tests/contract-fetch-multiple-big-map-keys.spec.ts
- integration-tests/lambda-view.spec.ts
- website/src/theme/CodeBlock/index.js
- website/src/theme/Playground/index.js
CLOSE #822 
Document for how to originate new contracts for the examples nad for tracking the changes:
https://docs.google.com/document/d/15rfuo70GkMHiKV_ChrRUbLcxOUo7S6hegQ4pzX21WlQ/edit?usp=sharing
> update taquito docs to florence

- example/tzip16-contract-origination-hostile-strings.ts
- [x ] Your code builds cleanly without any errors or warnings
This is to include in the examples the Taquito script for creating these kinds of contracts.
> add example for creating tzip16 metadata contract with hostile strings

- integration-tests/call-get-delegate-when-no-delegate.spec.ts
- integration-tests/contract-empty-delegated-implicit-account.spec.ts
- integration-tests/contract-manager-that-calls-failwith-contract.spec.ts
- integration-tests/contract-originate-token-contract.spec.ts
- integration-tests/contract-pair-as-key.spec.ts
- integration-tests/wallet-manager-that-calls-failwith-contract.spec.ts
- integration-tests/wallet-origination-wrong-order-code-properties.spec.ts
CLOSE #846 
- [X ] Your code builds cleanly without any errors or warnings
> Mk 846 add more jest retries to flaky tests

- packages/taquito-michelson-encoder/src/tokens/option.ts
- packages/taquito-michelson-encoder/test/tokens/map.spec.ts
- packages/taquito-michelson-encoder/test/tokens/option.spec.ts
> Made type "option" comparable

- integration-tests/contract-originate-token-contract.spec.ts
- integration-tests/wallet-api.spec.ts
CLOSE #842 
- [x ] Your code builds cleanly without any errors or warnings
> add retries to two tests

- packages/taquito-rpc/src/opkind.ts
- packages/taquito-rpc/src/types.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
> Added type for operation endorsement_with_slot

- integration-tests/call-get-delegate-when-no-delegate.spec.ts
- integration-tests/contract-register-delegate.spec.ts
- integration-tests/contract-set-delegate-auto-estimate.spec.ts
- integration-tests/contract-simple-delegation.spec.ts
- integration-tests/wallet-register-delegate.spec.ts
- integration-tests/wallet-set-delegate-auto-estimate.spec.ts
> fix error messages related to delegate

- integration-tests/config.ts
- integration-tests/contract-estimation-tests.spec.ts
- integration-tests/contract-originate-contract-with-sapling.spec.ts
- integration-tests/edo-deploy-contract-having-ticket.spec.ts
- integration-tests/edo-deploy-wallet-having-ticket.spec.ts
- integration-tests/wallet-originate-contract-with-sapling.spec.ts
> Added missing tests for galpha2net

- integration-tests/contract-estimation-tests.spec.ts
- integration-tests/local-forging.spec.ts
- integration-tests/package-lock.json
- integration-tests/package.json
- integration-tests/rpc-nodes.spec.ts
> Issue 817 missing tests

- packages/taquito-michelson-encoder/src/tokens/signature.ts
- packages/taquito-michelson-encoder/src/tokens/unit.ts
- packages/taquito-michelson-encoder/test/tokens/signature.spec.ts
- packages/taquito-michelson-encoder/test/tokens/unit.spec.ts
> Made type signature and type unit comparable

- example/contract-origination.ts
- example/contract-origination2.ts
- example/contract-origination3.ts
- example/contract-schema.ts
- example/example-activate.ts
- example/example-node.ts
- example/example-parallel-bigmap-local-vs-rpc-pack.ts
- example/example-sequential-bigmap-local-vs-rpc-pack.ts
- example/example-tzip16.ts
- example/package-lock.json
- example/package.json
- example/scan-path-ledger.ts
Updated the code examples for Taquito to work with Florencenet. All the tests passed successfully except for a few that are listed below as well as their error.
* example-activate.ts: 502 Error
* example-parallel-bigmap-local-vs-rpc-pack.ts: 502 Error (new contract successfully deployed on Florencenet)
* example-sequential-bigmap-local-vs-rpc-pack.ts: 502 Error (new contract successfully deployed on Florencenet)
* example-tzip16.ts: Dependency issue, "CryptoJS" module error even after running ```npm install``` for it directly
* scan-path-ledger.ts: The ```TransportNodeHid.create()``` function takes extremely long (30 mins+), on edonet and Florencenet
> issue-851: Updated Code Examples

- packages/taquito-michelson-encoder/src/tokens/or.ts
- packages/taquito-michelson-encoder/test/tokens/map.spec.ts
- packages/taquito-michelson-encoder/test/tokens/or.spec.ts
> Made the type "or" comparable and bug fix in the execute method

- docs/metadata-tzip16.md
Fixed a typo in the documentation and broken links to sequence diagrams
fix #878
> docs(tzip-016): fixed broken links

- .github/workflows/deploy_edge.yml
> fix PR comments failing in master

- docs/batch-api.md
Added more details to documentation following issue #887
> Added more details to documentation following issue #887

- packages/taquito/src/operations/batch-operation.ts
- packages/taquito/src/operations/index.ts
- packages/taquito/src/operations/operations.ts
- packages/taquito/src/operations/origination-operation.ts
- packages/taquito/src/taquito.ts
Export operation types
fix #583
> feat(taquito): export types

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> feat(beacon-wallet): update beacon-sdk to version 2.2.8

- website/docusaurus.config.js
> update doc config to show 9.1

- docs/version.md
> docs(version page): add release note for version 9.1.0

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> updated beacon-sdk to 2.2.9-beta.3

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
- packages/taquito-michelson-encoder/data/sample20.ts
- packages/taquito-michelson-encoder/src/schema/storage.ts
- packages/taquito-michelson-encoder/test/sample20.spec.ts
Validation was incorrect when value of a map is a big map
fix #925
> fix(michelson encoder - storage): fix type validation

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> Update beacon-sdk to version 2.2.9

- website/docusaurus.config.js
change the taquito docs version to 9.1.1
update website/docusaurus.config.js
> change the taquito docs version to 9.1.1

- integration-tests/contract-originate-contract-with-bls12-381-types.spec.ts
- packages/taquito-michelson-encoder/src/tokens/bls12-381-fr.ts
- packages/taquito-michelson-encoder/src/tokens/bls12-381-g1.ts
- packages/taquito-michelson-encoder/src/tokens/bls12-381-g2.ts
- packages/taquito-michelson-encoder/src/tokens/tokens.ts
- packages/taquito-michelson-encoder/test/tokens/bls12-381-fr.spec.ts
- packages/taquito-michelson-encoder/test/tokens/bls12-381-g1.spec.ts
- packages/taquito-michelson-encoder/test/tokens/bls12-381-g2.spec.ts
> Added tokens Bls12-381 to the Michelson Encoder

- integration-tests/ledger-signer.spec.ts
- integration-tests/multisig-contract-scenario.spec.ts
- integration-tests/tzip12-token-metadata.spec.ts
- integration-tests/tzip16-originate-contracts-with-metadata-on-itself-and-fetch-metadata.spec.ts
Corrected some typos in integration tests
> correct a few typos in integration tests

- integration-tests/package-lock.json
- package-lock.json
- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> Upgraded beacon-sdk version

- packages/taquito-rpc/src/types.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
> Support new fields introduced by Granada in block metadata (#918)

- .github/workflows/codeql-analysis.yml
Signed-off-by: Gino Imbrailo <ginoimbrailo@gmail.com>
> chore: changed codeql job to run on public runners

- packages/taquito/src/context.ts
- packages/taquito/test/context.spec.ts
> Fix confirmationPollingIntervalSecond for transition to Granada

- docs/quick_start.md
There are no code modifications, just an update to the docs.
> Remove InMemorySigner call and import

- packages/taquito-beacon-wallet/src/version.ts
- packages/taquito-http-utils/src/version.ts
- packages/taquito-ledger-signer/src/version.ts
- packages/taquito-local-forging/src/version.ts
- packages/taquito-michel-codec/src/version.ts
- packages/taquito-michelson-encoder/src/tokens/list.ts
- packages/taquito-michelson-encoder/src/version.ts
- packages/taquito-michelson-encoder/test/manager.spec.ts
- packages/taquito-michelson-encoder/test/proto005/multisig.spec.ts
- packages/taquito-michelson-encoder/test/sample1.spec.ts
- packages/taquito-michelson-encoder/test/sample10.spec.ts
- packages/taquito-michelson-encoder/test/sample21.spec.ts
- packages/taquito-michelson-encoder/test/sample6.spec.ts
- packages/taquito-michelson-encoder/test/tokens/lambda.spec.ts
- packages/taquito-remote-signer/src/version.ts
- packages/taquito-rpc/src/version.ts
- packages/taquito-signer/src/version.ts
- packages/taquito-tezbridge-signer/src/version.ts
- packages/taquito-tezbridge-wallet/src/version.ts
- packages/taquito-tzip12/src/version.ts
- packages/taquito-tzip16/src/version.ts
- packages/taquito-utils/src/version.ts
- packages/taquito/src/version.ts
> Issue-960 Changes for ExtractSchema for token type list

- integration-tests/rpc-get-protocol-constants.spec.ts
> Update integration test to fetch protocol constants on mainnet for proto10

- packages/taquito-michelson-encoder/src/tokens/ticket.ts
- packages/taquito-michelson-encoder/test/sample22.spec.ts
- packages/taquito-michelson-encoder/test/sample23_complex_ticket.spec.ts
> Issue-970 Added test cases and changes for ticket schema

- docs/set_delegate.md
- integration-tests/contract-set-delegate-auto-estimate.spec.ts
- packages/taquito/src/operations/types.ts
> Added support for the withdrawal of a delegate

- integration-tests/wallet-batch.spec.ts
- packages/taquito/src/wallet/batch-operation.ts
- packages/taquito/src/wallet/operation-factory.ts
- packages/taquito/src/wallet/wallet.ts
> Added a new BatchWalletOperation class which contains a status method

- packages/taquito-tzip16/src/tzip16-errors.ts
- packages/taquito-tzip16/test/viewKind/michelson-storage-view.spec.ts
> Pr1018 -  fix unit tests

- docs/rpc_nodes.md
closing #1023 with page update
> updated rpc docs page

- website/src/theme/CodeBlock/index.js
> Create a single instance of BeaconWallet on the Website

- packages/taquito/src/wallet/operation.ts
https://github.com/ecadlabs/taquito/issues/1040
> Unhandled MissedBlockDuringConfirmationError fix

- packages/taquito/src/operations/operations.ts
> Unhandled Confirmation  polling timed out fix - contract API

- website/src/pages/styles.module.css
>  Teams Building logos fixes on website #1068

- integration-tests/config.ts
> Use the new RpcClientCache into the integration tests

- docs/dapp_prelaunch.md
- website/sidebars.json
Added documentation for dapp prelaunch checklist
> Added documentation for dapp prelaunch checklist

- example/deploy-integration-tests-contracts.ts
- example/deploy-lambda-contract.ts
- example/example-Tzip12BigMapOffChain.ts
- integration-tests/config.ts
- integration-tests/contract-batch-register-global-constant.spec.ts
- integration-tests/contract-estimation-tests.spec.ts
- integration-tests/contract-originate-contract-with-chest.spec.ts
- integration-tests/contract-register-global-constant.spec.ts
- integration-tests/local-forging.spec.ts
- integration-tests/package-lock.json
- integration-tests/package.json
- integration-tests/rpc-get-protocol-constants.spec.ts
- packages/taquito-michel-codec/src/macros.ts
- packages/taquito-michel-codec/src/michelson-types.ts
- packages/taquito-rpc/src/taquito-rpc.ts
- packages/taquito-rpc/src/types.ts
- packages/taquito/src/constants.ts
> Replace PtHangzH with PtHangz2

- packages/taquito-rpc/package-lock.json
- packages/taquito-rpc/src/utils/utils.ts
> (rpc) Fix typo in lodash import

- example/deploy-docs-live-code-contracts.ts
closes #1193
Update the IPFS host URL in the contract origination script for live docs in /taquito/example
> change ipfs host address

- docs/michelsonmap.md
- docs/version.md
to close issue #1197 
fix two broken links in Taquito docs for v11
> fixed two links

- docs/michelsonmap.md
- example/example-contract-originate-Michelson-tutorial.ts
There is a link to a contract on BCD that is for the wrong chain and needs to be updated.
> fix contract reference in doc page

- example/deploy-docs-live-code-contracts.ts
Added MichelsonMap contract origination code.
Closes #1203
> add Michelsonmap contract to docs live code origination script

- docs/taquito_utils.md
- packages/taquito-utils/README.md
- packages/taquito-utils/src/taquito-utils.ts
- packages/taquito-utils/src/verify-signature.ts
- packages/taquito-utils/src/version.ts
- packages/taquito-utils/test/taquito-utils.spec.ts
- packages/taquito-utils/test/verify-signature.spec.ts
- website/sidebars.json
- website/src/theme/CodeBlock/index.js
> Added new util function and updated unit tests

- example/deploy-docs-live-code-contracts.ts
> rewrite check balances function in docs live code examples origination script

- typedoc.js
> Fixed taquito-contracts-library typedoc

- docs/global_constant.md
- integration-tests/contract-register-global-constant.spec.ts
- integration-tests/data/vote_contract_global_constant_storage.ts
- integration-tests/deploy-contract-having-global-constant-in-storage-part-script.spec.ts
- packages/taquito-michel-codec/src/micheline-parser.ts
- packages/taquito-michel-codec/test/global-constant.spec.ts
- packages/taquito-michel-codec/test/helpers/global-constants-helpers.ts
- packages/taquito-michelson-encoder/src/taquito-michelson-encoder.ts
- packages/taquito/src/context.ts
- packages/taquito/src/global-constants/default-global-constants-provider.ts
- packages/taquito/src/global-constants/error.ts
- packages/taquito/src/global-constants/interface-global-constants-provider.ts
- packages/taquito/src/global-constants/noop-global-constants-provider.ts
- packages/taquito/src/parser/michel-codec-parser.ts
- packages/taquito/src/taquito.ts
- packages/taquito/test/global-constants/default-global-constants-provider.spec.ts
- packages/taquito/test/parser/michel-codec-parser.spec.ts
- packages/taquito/test/taquito.spec.ts
> Expand global constant when encoding storage property

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> chore(beacon-wallet): updated beacon-sdk to v2.3.8

- docs/on_chain_views.md
- website/package-lock.json
- website/sidebars.json
> On-chain view documentation page

- typedoc.js
> Added google analytics tag to typedoc.js

- packages/taquito/src/taquito.ts
> Export ObservableSubscription class

- .eslintrc.json
- packages/taquito-http-utils/src/taquito-http-utils.ts
- packages/taquito-local-forging/src/decoder.ts
- packages/taquito-local-forging/src/schema/operation.ts
- packages/taquito-local-forging/test/allTestsCases.ts
- packages/taquito-michelson-encoder/src/michelson-map.ts
- packages/taquito-rpc/src/rpc-client-modules/rpc-cache.ts
- packages/taquito-rpc/src/taquito-rpc.ts
- packages/taquito-rpc/src/types.ts
- packages/taquito-tzip12/src/tzip12-contract-abstraction.ts
- packages/taquito-tzip16/src/composer.ts
- packages/taquito-tzip16/src/tzip16-contract-abstraction.ts
- packages/taquito/src/context.ts
- packages/taquito/src/contract/lambda-view.ts
- packages/taquito/src/signer/interface.ts
> style(eslint lint rules): enabled @typescript-eslint/ban-types rule

- package-lock.json
- package.json
> Downgraded typedoc

- integration-tests/README.md
CLOSE #1306
Update to the README for the integration test
light editing, clarification of some points,
addition of other ways to modify the test run
> Update to the README for the integration tests

- packages/taquito-local-forging/package-lock.json
- packages/taquito-local-forging/package.json
- packages/taquito-michel-codec/package-lock.json
- packages/taquito-michel-codec/package.json
- packages/taquito-michelson-encoder/package-lock.json
- packages/taquito-michelson-encoder/package.json
- packages/taquito-signer/package-lock.json
- packages/taquito-signer/package.json
- packages/taquito-tzip12/package-lock.json
- packages/taquito-tzip12/package.json
- packages/taquito-tzip16/package-lock.json
- packages/taquito-tzip16/package.json
- packages/taquito-utils/package-lock.json
- packages/taquito-utils/package.json
> Downgrade typedoc in all packages

- integration-tests/contract-call-with-xtz-amount.spec.ts
- integration-tests/local-forging.spec.ts
- packages/taquito-local-forging/src/constants.ts
- packages/taquito-local-forging/test/allTestsCases.ts
- packages/taquito-local-forging/test/data/contract_with_sub_mutez.ts
- packages/taquito-michel-codec/src/michelson-types.ts
> changes for new op codes - support SUB_MUTEZ in composite forger

- packages/taquito-rpc/package.json
- packages/taquito-rpc/src/rpc-client-modules/rpc-cache.ts
- packages/taquito-rpc/src/taquito-rpc.ts
- packages/taquito-rpc/test/rpc-cache.spec.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
- packages/taquito/src/wallet/wallet.ts
> Added more internal validation to various packages

- packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
- packages/taquito-contracts-library/src/errors.ts
- packages/taquito-http-utils/src/taquito-http-utils.ts
- packages/taquito-michelson-encoder/src/michelson-map.ts
- packages/taquito-michelson-encoder/src/schema/error.ts
- packages/taquito-michelson-encoder/src/tokens/createToken.ts
- packages/taquito-michelson-encoder/src/tokens/ticket.ts
- packages/taquito-michelson-encoder/src/tokens/token.ts
- packages/taquito-remote-signer/src/errors.ts
- packages/taquito-tezbridge-wallet/src/taquito-tezbridge-wallet.ts
- packages/taquito-tzip12/src/tzip12-errors.ts
- packages/taquito-tzip16/src/tzip16-errors.ts
- packages/taquito-utils/src/errors.ts
- packages/taquito/src/contract/errors.ts
- packages/taquito/src/forger/composite-forger.ts
- packages/taquito/src/global-constants/error.ts
- packages/taquito/src/operations/operation-errors.ts
- packages/taquito/src/signer/noop.ts
- packages/taquito/src/wallet/operation.ts
- packages/taquito/test/contract/contractView.spec.ts
Fixed custom errors to extend instead of implementing the Error class
Closes #973
> Issue 973 errors extend error

- docs/set_delegate.md
> Modified delegate documentation to differentiate setDelegate and registerDelegate

- .github/workflows/deploy_edge.yml
- .github/workflows/deploy_website.yml
- .github/workflows/main.yml
- .github/workflows/preview_website.yml
Ref #1365  
Remove caching steps in all Taquito workflows due to the problem mentioned in the referenced Issue
> Remove Caching steps in Taquito workflows

- website/README.md
Updated the website README to reflect current use cases
> Updated website readme content

- packages/taquito-rpc/README.md
- packages/taquito-signer/README.md
- packages/taquito-tzip12/README.md
- packages/taquito-tzip16/README.md
> Improved README tzip16, tzip12, signer and rpc

- packages/taquito-utils/README.md
- packages/taquito-utils/src/taquito-utils.ts
- packages/taquito-utils/test/taquito-utils.spec.ts
> Improved ReadMe utils package

- integration-tests/config.ts
- integration-tests/contract-call-with-xtz-amount.spec.ts
- integration-tests/contract-estimation-tests.spec.ts
- integration-tests/contract-originate-contract-with-sapling.spec.ts
- integration-tests/contract-originate-contract-with-single-sapling-state.spec.ts
- integration-tests/contract-sub-mutez.spec.ts
- integration-tests/contract-unit-as-param.spec.ts
- integration-tests/data/single_sapling_state_contract.ts
- integration-tests/data/single_sapling_state_contract_hangzhou.ts
- integration-tests/local-forging.spec.ts
- integration-tests/rpc-nodes.spec.ts
- integration-tests/wallet-unit-as-param.spec.ts
- packages/taquito-beacon-wallet/package-lock.json
> added three new rpc tests - two for Sapling and one for getNormalizedScript 

- README.md
> Added a note to readme about libudev

- README.md
- packages/taquito-tzip12/test/tzip12-contract-abstraction.spec.ts
- packages/taquito-tzip16/src/viewKind/michelson-storage-view.ts
- packages/taquito/src/contract/contract-methods/contract-on-chain-view.ts
- packages/taquito/src/contract/errors.ts
- packages/taquito/test/contract/contract-on-chain-view.spec.ts
> ViewSimulationError failwith property

- packages/taquito-michelson-encoder/README.md
- packages/taquito-remote-signer/README.md
- packages/taquito/README.md
> Improved README remote-signer, taquito and michelson-encoder

- docs/wallet_API.md
- website/src/theme/CodeBlock/index.js
- website/versioned_docs/version-11.2.0/wallet_API.md
> docs(wallet api): fixed "try beacon wallet" live code example

- integration-tests/rpc-nodes.spec.ts
- packages/taquito-contracts-library/src/rpc-wrapper.ts
- packages/taquito-rpc/src/rpc-client-interface.ts
- packages/taquito-rpc/src/rpc-client-modules/rpc-cache.ts
- packages/taquito-rpc/src/taquito-rpc.ts
- packages/taquito-rpc/src/types.ts
- packages/taquito-rpc/test/data/rpc-responses.ts
- packages/taquito-rpc/test/rpc-cache.spec.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
> feat(rpc): added support for protocols endpoint

- docs/quick_start.md
Closes #1383 
update link in docs/quick_start to where to get faucet keys files
> updated link to faucet files

- docs/rpc_nodes.md
- website/yarn.lock
I have partially implemented this.
I have converted the list to a table.
I have added a link to check that the node is viable by pulling the header.
The adding of live code to the show level and protocol will be done in a separate issue.
> converted rpc node list to table

- docs/estimate.md
- docs/ledger_signer.md
- docs/making_transfers.md
- docs/maps_bigmaps.md
- docs/metadata-tzip16.md
- docs/on_chain_views.md
- docs/originate.md
- docs/quick_start.md
- docs/smartcontracts.md
- docs/storage_annotations.md
- docs/tzip12.md
- example/wallet-originate-areyouthere.ts
- website/yarn.lock
> add wallet examples to live code in docs

- packages/taquito-contracts-library/src/rpc-wrapper.ts
- packages/taquito-rpc/src/rpc-client-interface.ts
- packages/taquito-rpc/src/rpc-client-modules/rpc-cache.ts
- packages/taquito-rpc/src/taquito-rpc.ts
- packages/taquito-rpc/src/types.ts
> Add support for the runView endpoint in the RpcClient

- packages/taquito-utils/src/verify-signature.ts
- packages/taquito/src/signer/interface.ts
Not for release till Ithaca
CLOSES #1257
> Ithaca magic bytes doc in comment change - updated magic bytes comment in two files

- packages/taquito-contracts-library/src/read-provider-wrapper.ts
- packages/taquito/src/read-provider/interface.ts
- packages/taquito/src/read-provider/rpc-read-adapter.ts
- packages/taquito/src/wallet/operation-factory.ts
- packages/taquito/src/wallet/operation.ts
- packages/taquito/test/read-provider/data.ts
- packages/taquito/test/read-provider/rpc-read-adapter.spec.ts
- packages/taquito/test/wallet/operation.spec.ts
> Read interface added missing methods

- packages/taquito/src/batch/rpc-batch-provider.ts
- packages/taquito/src/context.ts
- packages/taquito/src/contract/interface.ts
- packages/taquito/src/contract/rpc-contract-provider.ts
- packages/taquito/src/estimate/estimate-provider-interface.ts
- packages/taquito/src/estimate/estimate.ts
- packages/taquito/src/estimate/index.ts
- packages/taquito/src/estimate/naive-estimate-provider.ts
- packages/taquito/src/estimate/rpc-estimate-provider.ts
- packages/taquito/src/operations/operation-emitter.ts
- packages/taquito/src/taquito.ts
- packages/taquito/test/batch/rpc-batch-provider.spec.ts
- packages/taquito/test/contract/rpc-contract-provider.spec.ts
- packages/taquito/test/estimate/estimate.spec.ts
- packages/taquito/test/estimate/rpc-estimate-provider.spec.ts
- packages/taquito/test/taquito.spec.ts
> refactor(estimate): moved all estimate files in a separate folder

- website/config.json
> Removed certain domains to optimize search results as well as indexing cost

- packages/taquito/src/wallet/delegation-operation.ts
> fix(wallet delegation): fixed delegationOperation return type

- docs/upgrading_guide.md
- packages/taquito/src/contract/contract.ts
- packages/taquito/test/contract/contractView.spec.ts
> docs(upgrade guide v12): describe breaking changes in version 12

- packages/taquito-michelson-encoder/src/tokens/pair.ts
- packages/taquito-michelson-encoder/test/tokens/constant.spec.ts
- packages/taquito-michelson-encoder/test/tokens/pair.spec.ts
> fix(michelson-encoder): fix pair indexes in extract schema

- .github/workflows/algolia.yml
Notify `#algolia_github` Slack channel whenever the Algolia indexing job fails or succeeds.
Confirmed that notifications are triggered for successful and failed jobs
> Slack Notification for Algolia Indexing jobs

- website/src/components/CardsGrid/CardsGrid.module.scss
- website/src/components/Hero/Hero.module.scss
- website/src/components/SimpleStep/SimpleStep.js
- website/src/components/SimpleStep/SimpleStep.module.scss
- website/src/components/SimpleWay/SimpleWay.module.scss
- website/src/css/custom.scss
- website/src/pages/index.js
> Simple steps module

- docs/contract-test-collection.md
- website/docusaurus.config.js
- website/src/css/custom.scss
- website/src/css/tables.scss
> adjust sidebars

- integration-tests/contract-originate-contract-with-single-sapling-state.spec.ts
> Fix single sapling state contract for protocol J

- integration-tests/rpc-nodes.spec.ts
> Fix test getSaplingDiffById

- website/src/components/TeamsCarousel/TeamsCarousel.js
- website/src/components/TitleBlock/TitleBlock.js
- website/src/css/custom.scss
> New corrections after design 

- .eslintrc.json
- package-lock.json
- packages/taquito-http-utils/src/taquito-http-utils.ts
- packages/taquito-local-forging/src/michelson/codec.ts
- packages/taquito-local-forging/src/validator.ts
- packages/taquito-local-forging/test/allTestsCases.ts
- packages/taquito-local-forging/test/data/generic_contract.ts
- packages/taquito-rpc/src/rpc-client-interface.ts
- packages/taquito-rpc/src/rpc-client-modules/rpc-cache.ts
- packages/taquito-utils/src/taquito-utils.ts
- packages/taquito-utils/src/validators.ts
- packages/taquito-utils/test/validators.spec.ts
- packages/taquito/src/contract/contract.ts
- website/package-lock.json
some changes as a start so the PR isnt very large 
all tests pass and build properly but definitely would like more eyes on it to make sure I havent changed too much 😄 
> Start eslint any

- website/versioned_docs/version-12.1.0/rpc_nodes.md
Add Marigold Tezos nodes in `rpc_nodes` docs.
> Add marigold tezos nodes

- docs/rpc_nodes.md
- package-lock.json
- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-contracts-library/package-lock.json
- packages/taquito-http-utils/package-lock.json
- packages/taquito-ledger-signer/package-lock.json
- packages/taquito-local-forging/package-lock.json
- packages/taquito-michel-codec/package-lock.json
- packages/taquito-michelson-encoder/package-lock.json
- packages/taquito-remote-signer/package-lock.json
- packages/taquito-rpc/package-lock.json
- packages/taquito-signer/package-lock.json
- packages/taquito-tezbridge-signer/package-lock.json
- packages/taquito-tezbridge-wallet/package-lock.json
- packages/taquito-tzip12/package-lock.json
- packages/taquito-tzip16/package-lock.json
- packages/taquito-utils/package-lock.json
- packages/taquito/package-lock.json
- website/docusaurus.config.js
- website/src/css/custom.scss
- yarn.lock
> updated rpc nodes and made modifications to navbar components

- docs/making_transfers.md
Fixed the broken link
CLOSE #1629
> corrected link to integration test

- packages/taquito-rpc/test/data/rpc-responses.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
> added unit test for tx_rollup_finalize_commitment

- .github/workflows/tezedge.yml
Ref #1446
Run Taquito integration tests against a Tezedge node.
> [ci] Run integration tests against a Tezedge node

- website/src/css/codeBlock.scss
- website/src/theme/CodeBlock/styles.module.css
- website/src/theme/Playground/index.js
- website/src/theme/Playground/styles.module.css
fix code snippets and live code examples
> adjust css and fix background overlay to hid cursor and highlight

- integration-tests/ledger-signer-failing-tests.spec.ts
CLOSE #1694 
Change 
Unable to retrieve public key
to
Unable to retrieve public key from Ledger
> fix test assert

- docs/estimate.md
correct the live code example for estimation
CLOSE #1693
> fix live code in docs estimation example

- docs/rpc_nodes.md
Hi, please consider adding a link to MIDL.dev Tezos RPC service to the Taquito documentation
> Add MIDL.dev commercial RPC service to Taquito doc

- website/package-lock.json
- website/yarn.lock
> Revert "Bump parse-url from 6.0.0 to 6.0.2 in /website"

- packages/taquito-michelson-encoder/src/tokens/comparable/bytes.ts
- packages/taquito-michelson-encoder/test/tokens/bytes.spec.ts
- packages/taquito-utils/src/taquito-utils.ts
- yarn.lock
> added support for 0x prefix hex string in michelson encoder

- integration-tests/config.ts
- integration-tests/contract-batch.spec.ts
- integration-tests/rpc-taquito.spec.ts
- integration-tests/wallet-batch.spec.ts
- packages/taquito/src/operations/batch-operation.ts
- packages/taquito/src/wallet/batch-operation.ts
- packages/taquito/test/data/batch-results.ts
- packages/taquito/test/operations/batch-operation.spec.ts
- packages/taquito/test/wallet/batch-wallet-operation.spec.ts
- yarn.lock
#1661 
- Added member function to retrieve batched originated contract addresses
- Updated integration tests
> Add member function that retrieves originated contract addresses

- docs/rpc_nodes.md
- integration-tests/rpc-nodes.spec.ts
Closes #1779 
update to include ghostnet and kathmandunet and deprecate ithacanet
> updated community run rpc nodes list for taquito docs

- website/yarn.lock
> regenerate package-lock

- packages/taquito-rpc/src/types.ts
- packages/taquito-rpc/test/data/rpc-responses.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
> test: added unit test for tx_rollup_rejection

- .github/workflows/bundle_webpack.yml
- docs/mobile_bundle.md
- example/package-lock.json
- integration-tests/package-lock.json
- package-lock.json
- package.json
- packages/taquito-local-forging/package-lock.json
- packages/taquito-local-forging/package.json
- packages/taquito-local-forging/webpack.config.js
- packages/taquito-michel-codec/pack-test-tool/package-lock.json
- website/sidebars.js
- website/sidebars.json
- website/yarn.lock
- yarn.lock
> Added new webpack config bundle and updated docs

- docs/liquidity_baking.md
> Fix error example doc liquidity baking

- packages/taquito/src/batch/rpc-batch-provider.ts
- packages/taquito/src/contract/prepare.ts
- packages/taquito/src/contract/rpc-contract-provider.ts
- packages/taquito/src/estimate/estimate-provider-interface.ts
- packages/taquito/src/estimate/rpc-estimate-provider.ts
- packages/taquito/src/operations/operation-emitter.ts
- packages/taquito/src/operations/operation-errors.ts
- packages/taquito/src/operations/transaction-operation.ts
- packages/taquito/src/operations/transfer-ticket-operation.ts
- packages/taquito/src/operations/types.ts
- packages/taquito/test/contract/helper.ts
- packages/taquito/test/contract/rpc-contract-provider.spec.ts
- packages/taquito/test/estimate/rpc-estimate-provider.spec.ts
- packages/taquito/test/helpers.ts
- packages/taquito/test/operations/transfer-ticket-operation.spec.ts
> Tx rollup transfer op

- .github/workflows/main.yml
- docs/sapling.md
- docs/sapling_in_memory_spending_key.md
- docs/sapling_in_memory_viewing_key.md
- integration-tests/package.json
- integration-tests/sapling-batched-transactions.spec.ts
- integration-tests/sapling-transactions.spec.ts
- packages/taquito-sapling/README.md
- packages/taquito-sapling/src/taquito-sapling.ts
- packages/taquito-tzip16/test/viewKind/michelson-storage-view.spec.ts
- packages/taquito/src/context.ts
- packages/taquito/src/read-provider/rpc-read-adapter.ts
- packages/taquito/src/taquito.ts
- packages/taquito/test/contract/contract-abstraction-composer.spec.ts
- packages/taquito/test/contract/contract-on-chain-view.spec.ts
- packages/taquito/test/contract/lambda-view-class.spec.ts
- packages/taquito/test/read-provider/rpc-read-adapter.spec.ts
- packages/taquito/test/wallet/contract-abstraction-composer-wallet.spec.ts
- typedoc.js
- website/plugins/webpack5plugin/index.js
- website/sidebars.js
- website/sidebars.json
> docs(sapling): documentation for the sapling package

- integration-tests/sapling-transactions-contract-with-multiple-sapling-states.spec.ts
- integration-tests/sapling-transactions-contract-with-single-state.spec.ts
- packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
An integration test to interact with a contract having 2 sapling pools
re #1825
> test(integration tests): sapling multiple states test

- integration-tests/http-backend-request-error-handling.spec.ts
- packages/taquito-http-utils/src/taquito-http-utils.ts
- packages/taquito-rpc/src/opkind.ts
- packages/taquito-rpc/src/types.ts
- packages/taquito-rpc/test/data/rpc-responses.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
> 1848-added types for increase paid storage

- .github/workflows/algolia.yml
Fixed algolia indexing errors by updating the node version
> Update node algolia

- packages/taquito-remote-signer/test/taquito-remote-signer.spec.ts
This is a redo of another Pr
Close #1804
> mk-1804-Add unit tests to taquito-remote-signer

- docs/beaconwallet-singleton.md
- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
- packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
> Bump beacon 3.1.4

- .github/workflows/mondaynet.yml
- integration-tests/config.ts
- integration-tests/data/tickets_deposit_contract.ts
- integration-tests/data/tickets_withdrawal_contract.ts
- integration-tests/tx-rollup-transfer-ticket.spec.ts
- packages/taquito-michelson-encoder/package-lock.json
- packages/taquito/src/contract/interface.ts
- packages/taquito/src/operations/transfer-ticket-operation.ts
> Mondaynet transfer ticket integration test

- website/versioned_docs/version-14.0.0/complex_parameters.md
- website/versioned_docs/version-14.0.0/estimate.md
- website/versioned_docs/version-14.0.0/lambda_view.md
- website/versioned_docs/version-14.0.0/ledger_signer.md
- website/versioned_docs/version-14.0.0/making_transfers.md
- website/versioned_docs/version-14.0.0/maps_bigmaps.md
- website/versioned_docs/version-14.0.0/metadata-tzip16.md
- website/versioned_docs/version-14.0.0/michelsonmap.md
- website/versioned_docs/version-14.0.0/on_chain_views.md
- website/versioned_docs/version-14.0.0/quick_start.md
- website/versioned_docs/version-14.0.0/smartcontracts.md
- website/versioned_docs/version-14.0.0/tzip12.md
- website/versioned_docs/version-14.0.0/wallet_API.md
> Recreated version 14 of the doc to include Kathmandunet changes

- integration-tests/contract-estimation-tests.spec.ts
- integration-tests/contract-extensions.spec.ts
- integration-tests/contract-failwith.spec.ts
- integration-tests/contract-lambda-view.spec.ts
- integration-tests/contract-ligo-increment-contract.spec.ts
> pr split five - add five files

- packages/taquito-beacon-wallet/package.json
- packages/taquito-beacon-wallet/test/mock-local-storage.ts
- packages/taquito-beacon-wallet/test/taquito-beacon-wallet.spec.ts
Close #1935 
this is a REDO of another PR that had build problems
> add unit test files for beacon wallet package

- integration-tests/contract-empty-implicit-account-into-new-implicit-account.spec.ts
- integration-tests/contract-execute-on-chain-view.spec.ts
- integration-tests/contract-increase-paid-storage-operation.spec.ts
- integration-tests/injecting-multiple-manager-operations-in-a-block.spec.ts
- integration-tests/local-forging.spec.ts
- integration-tests/rpc-get-protocol-constants.spec.ts
- integration-tests/rpc-nodes.spec.ts
> Ensure tests that run on kathmandunet also run on mondaynet(alpha)

- packages/taquito/src/contract/contract-methods/contract-on-chain-view.ts
I only reversed the logic of the if/else statements to execute the old implementation using runCode only when the protocol is Jakarta. We can remove the if/else statements when we stop running our integration tests against jakartanet.
> Fix issue when executing on chain view with protocol alpha

- integration-tests/README.md
- integration-tests/config.ts
- integration-tests/package.json
> Added env var for polling interval and rpc cache ttl

- example/package-lock.json
- integration-tests/package-lock.json
- integration-tests/sapling-transactions-contract-with-single-state.spec.ts
- package-lock.json
- packages/taquito-contracts-library/package-lock.json
- packages/taquito-ledger-signer/package-lock.json
- packages/taquito-local-forging/package-lock.json
- packages/taquito-michelson-encoder/package-lock.json
- packages/taquito-remote-signer/package-lock.json
- packages/taquito-rpc/package-lock.json
- packages/taquito-sapling/package-lock.json
- packages/taquito-signer/package-lock.json
- packages/taquito-tzip16/package-lock.json
- packages/taquito/package-lock.json
- website/package-lock.json
- website/yarn.lock
CLOSE #1952   
Change the fixed address to a dynamically generated one to help stability for the test
> change address in sapling test to dynamically generated one

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> Bump airgap/beacon-dapp to version 3.2.0

- README.md
I learned from Zainen that node 16.13.1 works but greater than 16.13.1 does not, so we should be specific here....
> Be version-specific for supported node releases

- integration-tests/contract-originate-timestamp-storage.spec.ts
- packages/taquito-local-forging/src/michelson/codec.ts
- packages/taquito-michelson-encoder/src/tokens/comparable/timestamp.ts
- packages/taquito-michelson-encoder/test/tokens/timestamp.spec.ts
> fixed michelson encoder for timestamp to handle numbers being passed

- packages/taquito-http-utils/src/taquito-http-utils.ts
> patch(http-utils): Awaited imported fetch adapter

- docs/ledger_signer.md
- integration-tests/data/contract_origination.ts
- integration-tests/ledger-signer.spec.ts
- integration-tests/package-lock.json
- integration-tests/package.json
- package-lock.json
- packages/taquito-ledger-signer/README.md
- packages/taquito-ledger-signer/package.json
- packages/taquito-ledger-signer/src/taquito-ledger-signer.ts
- packages/taquito-ledger-signer/src/utils.ts
- packages/taquito-ledger-signer/test/taquito-ledger-signer.spec.ts
- tsconfig.base.json
- website/yarn.lock
- yarn.lock
add support for use of ledger bip32_ed25519 tz1 addresses 
ability to connect taquito-ledger-signer to ledger using dervationType.bip32_ed25519
> 1869 bip32 support

- docs/rpc_nodes.md
> Updated rpc node list to include limanet

- packages/taquito-rpc/test/data/rpc-responses.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
> added test for tx_rollup_return_bond

- packages/taquito-beacon-wallet/package-lock.json
- packages/taquito-beacon-wallet/package.json
> Bump @airgap/beacon-dapp to v 3.3.0

- apps/taquito-test-dapp/package-lock.json
- apps/taquito-test-dapp/package.json
> Update taquito-test-dapp with taquito version 14.1.0-beta-RC.0

- packages/taquito-rpc/src/types.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
- packages/taquito/src/constants.ts
> 2069 type changes

- integration-tests/config.ts
- integration-tests/contract-estimation-tests.spec.ts
> Replace lima rpc url in test

- integration-tests/fromMnemonic-send-tez.spec.ts
add catch for failure to see the mnemonic when method fails
> add try catch to show error as well as mnemonic

- integration-tests/contract-estimation-tests.spec.ts
- integration-tests/contract-tx-rollup-batch-operation.spec.ts
> fix(integration-tests): fix tests for lima

- integration-tests/rpc-get-protocol-constants.spec.ts
- packages/taquito-rpc/src/types.ts
- packages/taquito-rpc/test/taquito-rpc.spec.ts
> fix(rpc): add missing properties related to lima

- integration-tests/injecting-multiple-manager-operations-in-a-block.spec.ts
- integration-tests/rpc-nodes.spec.ts
> test(integration-test): small clean up and remove duplication

- integration-tests/injecting-multiple-manager-operations-in-a-block.spec.ts
> Try fix test

- docs/consensus_key.md
- website/sidebars.js
- website/sidebars.json
> Consensus key docs

- integration-tests/contract-security-duplicate-ticket.spec.ts
- integration-tests/contract-security-tickets-duplication.spec.ts
- integration-tests/rpc-get-protocol-constants.spec.ts
> Mondaynet 2022 12 05

- docs/version.md
- website/versioned_docs/version-15.0.0/version.md
Updates release notes to include patch release v15.0.1
> added release notes for patch release 15.0.1

- .github/workflows/deploy_edge.yml
Fix NPM preview packages published to https://npm.preview.tezostaquito.io/
> Fix NPM preview package deployment

- integration-tests/known-contracts-ProtoALph.ts
- integration-tests/rpc-get-protocol-constants.spec.ts
one constant change and update known contracts
> one constant change

- integration-tests/wallet-increase-paid-storage-operation.spec.ts
- packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
- packages/taquito/src/wallet/increase-paid-storage-operation.ts
- packages/taquito/src/wallet/interface.ts
- packages/taquito/src/wallet/legacy.ts
- packages/taquito/src/wallet/operation-factory.ts
- packages/taquito/src/wallet/wallet.ts
- packages/taquito/test/wallet/increase-paid-storage-operation.spec.ts
closes #1768 
adds increase_paid_storage operation to Wallets functionality 
includes integration test and unit test
> 1768 wallet increase paid storage

- package-lock.json
- packages/taquito-http-utils/package.json
- packages/taquito-http-utils/src/taquito-http-utils.ts
> add extra case to handle axios-fetch-adapter error response

- integration-tests/known-contracts-ProtoALph.ts
all tests passing just needs new contracts
> update contracts mondaynet

- apps/taquito-test-dapp/package.json
- packages/taquito-beacon-wallet/package.json
Updated Beacon version to v3.3.1
> updated beacon version

- integration-tests/known-contracts-ProtoALph.ts
> chore: update mondaynet contracts

- packages/taquito/src/contract/rpc-contract-provider.ts
fix wrong type doc type
closes #2327
> chore: fix wrong typedoc type

- integration-tests/contract-override-estimate.spec.ts
- integration-tests/contract-simple-origination.spec.ts
- packages/taquito/src/operations/index.ts
- packages/taquito/src/operations/operation-emitter.ts
- packages/taquito/src/operations/operation-errors.ts
- packages/taquito/test/estimate/rpc-estimate-provider.spec.ts
closes #2318 
- Update the estimate process to have a validation step to ensure no decimal values are being passed
- Updated integration tests
> 2318 estimate decimal

- README.md
- integration-tests/README.md
- website/README.md
- Fixed a type where referring to integration-tests/sandbox-env.sh
- Removed $ in some shell commands for consistency
- Changed Kathmandu to Lima for tests
> Improvements to README files

- .github/workflows/main.yml
- integration-tests/config.ts
Flextesa Docker image version `20230203` now includes the Mumbai protocol. This PR adds support for running integration tests against a Mumbai Flextesa sandbox
> Run integration tests against Flextesa Mumbainet

- docs/maps_bigmaps.md
- docs/on_chain_views.md
- example/deploy-docs-live-code-contracts.ts
- website/versioned_docs/version-15.1.0/maps_bigmaps.md
- website/versioned_docs/version-15.1.0/on_chain_views.md
https://17d1169--tezostaquito.netlify.app/docs/next/maps_bigmaps
https://17d1169--tezostaquito.netlify.app/docs/next/on_chain_views/
closes #2305 
> 2305 website broken live code

- example/scan-path-ledger.ts
after a review of the Taquito examples the ledger example needs to be updated to work with Ghostnet.
the rest are already done and working.
> update ledger example to ghostnet

- website/package.json
- website/src/theme/Footer/index.js
Updates Docusaurus to its latest stable version and made relevant adjustments
> updated docusaurus to latest version

- .github/workflows/main.yml
- integration-tests/injecting-multiple-manager-operations-in-a-block.spec.ts
- integration-tests/sandbox-ballot-operation.spec.ts
- integration-tests/sandbox-drain-delegate-operation.spec.ts
- updated tests to comply with octez v16
- upgraded flextesa sandbox to include Mumbai2 protocol change
> updated tests and upgraded flextesa image

- docs/rpc_nodes.md
removed kathmandunet and added ghostnet and mumbainet where applicable 
closes #2407 
> 2407 update website listed nodes

- integration-tests/data/allTestsCases.ts
> test: combine mumbai test cases with all test cases

- waku-helpers.sh
Shell helpers for WC2 development, specifically [waku](https://waku.org/platform) interaction. With it, you can start a waku node, subscribe to topics, publish messages to a given topic, receive new messages from a given topic, and unsubscribe. These primitives can be used for diagnostics, test automation, and so forth.
> Waku scratchings

- docs/rpc_nodes.md
- website/versioned_docs/version-14.1.0/rpc_nodes.md
- website/versioned_docs/version-14.2.0/rpc_nodes.md
- website/versioned_docs/version-15.0.0/rpc_nodes.md
- website/versioned_docs/version-15.1.0/rpc_nodes.md
- website/versioned_docs/version-16.0.0/rpc_nodes.md
Add Exaion node application as Rpc commercial provider.
You can find Exaion blockchain services at https://node.exaion.com
> Doc : Add Exaion node as commercial provider

- docs/estimate.md
- integration-tests/contract-call-estimate.spec.ts
- packages/taquito/src/estimate/estimate-provider-interface.ts
- packages/taquito/src/estimate/rpc-estimate-provider.ts
- packages/taquito/test/contract/rpc-contract-provider.spec.ts
- packages/taquito/test/estimate/rpc-estimate-provider.spec.ts
closes #2019 
- Added support for contractCall estimation
- Updated unit and integration tests
- Updated documentation
> 2019 call estimate

- docs/local_forger.md
- website/sidebars.js
- website/sidebars.json
Adds a document describing how to use the local forger.
> add doc for local forger

- packages/taquito-http-utils/package.json
- packages/taquito-http-utils/src/taquito-http-utils.ts
> updated npm package to a published version

- packages/taquito-rpc/src/types.ts
fix two wrong types put as number should be string
closes #2440 bug ticket
> fix: fix types put as number that should be string

- integration-tests/polling-subscribe-provider.spec.ts
> Improve event filter testing

- integration-tests/README.md
updated the readme for integration tests to work for Mumbai net
dropped the flextesa explanation as that needs rewriting and will be done in separate PR.
closes #2459
> revised integration test readme

- apps/taquito-test-dapp/src/lib/Wallet.svelte
> Change projectId in test dapp

- apps/taquito-test-dapp/package.json
- apps/taquito-test-dapp/src/App.svelte
- apps/taquito-test-dapp/src/lib/Wallet.svelte
- package-lock.json
- packages/taquito-beacon-wallet/package.json
- packages/taquito-beacon-wallet/signature.json
- website/package-lock.json
> Beacon sdk 4.0.2

- docs/smartcontracts.md
CLOSES #2482 
updated the smart contract page to use jsligo contract, as suggested by b. Fuentes
also originated the new contract to work with the live code examples
> updated smart contract doc with JSLigo example

- packages/taquito-http-utils/src/taquito-http-utils.ts
> Fix broken isNode check

- integration-tests/README.md
added keygen diagram to integration test readme
and some descriptive text
CLOSES #2503
> added keygen diagram to integration test readme

- website/package-lock.json
- website/package.json
> update sass and dotenv versions

- docs/local_forger.md
> updated local forger documentation to include recent changes

- apps/taquito-test-dapp/package.json
- apps/taquito-test-dapp/src/lib/Wallet.svelte
- docs/originate.md
- docs/wallet_API.md
- package-lock.json
- packages/taquito-beacon-wallet/package.json
- website/package-lock.json
- website/src/theme/CodeBlock/index.js
- website/src/theme/Playground/index.js
- website/versioned_docs/version-17.1.0/wallet_API.md
> updated beacon version to 4.0.6

- apps/taquito-test-dapp/src/tests.ts
- integration-tests/contract-failing-noop.spec.ts
- integration-tests/wallet-failing-noop.spec.ts
- packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
- packages/taquito-beacon-wallet/test/taquito-beacon-wallet.spec.ts
- packages/taquito/src/wallet/interface.ts
- packages/taquito/src/wallet/legacy.ts
- packages/taquito/src/wallet/wallet.ts
> fix beacon wallet's sign bug

- LICENSE
- NOTICE
- website/src/theme/CodeBlock/index.js
- website/src/theme/DocPageLayoutMain.tsx
- website/src/theme/Footer/index.js
- website/src/theme/Footer/styles.module.css
- website/src/theme/Playground/index.js
- website/src/theme/Playground/styles.module.css
> Changed license from MIT to Apache 2.0

- package-lock.json
- packages/taquito-beacon-wallet/package.json
- packages/taquito-contracts-library/package.json
- packages/taquito-core/package.json
- packages/taquito-http-utils/package.json
- packages/taquito-ledger-signer/package.json
- packages/taquito-local-forging/package.json
- packages/taquito-michel-codec/pack-test-tool/package.json
- packages/taquito-michelson-encoder/package.json
- packages/taquito-remote-signer/package.json
- packages/taquito-rpc/package.json
- packages/taquito-sapling/package.json
- packages/taquito-signer/package.json
- packages/taquito-tzip12/package.json
- packages/taquito-tzip16/package.json
- packages/taquito-utils/package.json
- packages/taquito/package.json
> Align our license in package.json files

- integration-tests/rpc-get-protocol-constants.spec.ts
- packages/taquito-rpc/src/types.ts
closes #2594 
updated oxford protocol constant response type and integration test 
> 2594 oxford protocol constants update

- .github/workflows/main.yml
> Oxford pr run with flextesa

- apps/taquito-test-dapp/package.json
- package-lock.json
- packages/taquito-beacon-wallet/package.json
- packages/taquito-beacon-wallet/signature.json
- website/package-lock.json
> update to beacon-sdk-4-0-10

- packages/taquito/src/estimate/rpc-estimate-provider.ts
> style(rpcestimateprovider): minor typo fix

- docs/ophash_before_injecting.md
- website/sidebars.js
- website/versioned_docs/version-17.3.0/ophash_before_injecting.md
- website/versioned_sidebars/version-17.3.0-sidebars.json
> added docs on obtaining ophash before injecting

- package-lock.json
- packages/taquito-tzip16/package.json
- website/package-lock.json
> chore: dependabot update

- docs/rpc_nodes.md
- website/versioned_docs/version-17.3.0/rpc_nodes.md
- website/versioned_docs/version-17.4.0/rpc_nodes.md
update website rpc nodes page removed TezTools add TzPro
> docs: website-rpc-nodes-update

- apps/taquito-test-dapp/package.json
- package-lock.json
- packages/taquito-beacon-wallet/package.json
- packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts
> updated beacon version to 4.1.2

- website/docusaurus.config.js
- website/src/theme/SearchPage/index.js
- website/src/theme/SearchPage/styles.module.css
> 2858 ux improvements to search

- docs/tutorial.md
> simplify tutorial for browser-based dApps

- docs/staking.md
- website/sidebars.js
> Documentation for Staking

- apps/taquito-test-dapp/package.json
- package-lock.json
- packages/taquito-beacon-wallet/package.json
- website/package-lock.json
- website/versioned_docs/version-17.4.0/batch-api.md
> Update Paris branch with newest Beacon version (v4.2.2-beta.4)

- apps/taquito-test-dapp/src/tests.ts
Text changes needed for Taquito Test Dapp
> text changes for Taquito Test Dapp

- package-lock.json
- website/package.json
removed remaining netlify references in the codebase (we migrated to Cloudflare)
> removed netlify refs

- packages/taquito-rpc/src/types.ts
> fix: add baker_own_stake to FrozenStaker

- docs/contract-test-collection.md
- integration-tests/data/metadataViews.ts
- integration-tests/data/smartpy-example-contract.ts
- packages/taquito-beacon-wallet/src/errors.ts
> chore: fix some typos in comment

- .github/workflows/main.yml
- package-lock.json
> Ci lts/jod

- .github/workflows/deploy_website.yml
Deploying website to Cloudflare Pages to automate deployment process on push and pull request events
> feat(workflow): add GitHub Actions workflow for CloudFlare pages
